create table if not exists rooms (
  code text primary key,
  title text not null default 'Upper City 30H',
  created_at timestamptz not null default now()
);
create table if not exists players (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  name text not null,
  class_name text,
  last_seen timestamptz default now(),
  created_at timestamptz not null default now(),
  unique(room_code,name)
);
create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_code text not null references rooms(code) on delete cascade,
  sender text not null,
  body text not null,
  kind text not null default 'action',
  created_at timestamptz not null default now()
);
alter table rooms enable row level security;
alter table players enable row level security;
alter table messages enable row level security;
drop policy if exists "rooms public demo" on rooms;
drop policy if exists "players public demo" on players;
drop policy if exists "messages public demo" on messages;
create policy "rooms public demo" on rooms for all using (true) with check (true);
create policy "players public demo" on players for all using (true) with check (true);
create policy "messages public demo" on messages for all using (true) with check (true);
do $$ begin
 alter publication supabase_realtime add table players;
exception when duplicate_object then null; end $$;
do $$ begin
 alter publication supabase_realtime add table messages;
exception when duplicate_object then null; end $$;
