import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$ select current_setting('app.uid',true)::uuid $$;create publication supabase_realtime;create function gen_random_bytes(int) returns bytea language sql as $$ select decode(substr(md5(random()::text),1,$1*2),'hex') $$;");
const migrations=['supabase.sql','upgrade.sql',...['002_secure_campaign','003_encounters','004_campaign_battles','005_classes_spells','006_deeper_campaign','007_upper_city_areas','008_v21_combat_story','009_v21_dialogue_polish','010_v22_save_slots','011_xp_progression','012_v30_story_depth','013_v30_battle_aftermath','014_v30_followup_dialogue','015_v30_encounter_routes','016_v31_stability_finale','017_v31_saved_room_lobby','018_v40_identity_rules','019_v40_world_build','020_v40_racial_combat','021_v40_final_battle','022_v40_rules_bridge','023_v40_companion','024_v40_companion_actions','025_v40_faction_reputation','026_v40_enemy_ai','027_v40_identity_dialogue','028_v40_final_environment_guard'].map(name=>`db/${name}.sql`)];
for(const file of migrations)await db.exec(fs.readFileSync(file,'utf8').replace('create extension if not exists pgcrypto;',''));
const ids=['00000000-0000-0000-0000-0000000000a1','00000000-0000-0000-0000-0000000000a2'];
for(const id of ids)await db.query('insert into auth.users(id) values($1)',[id]);
async function as(i,sql,args=[]){await db.query("select set_config('app.uid',$1,false)",[ids[i]]);return (await db.query(sql,args)).rows[0]?.v}
async function cmd(i,room,action,payload={}){return as(i,'select public.party_v4_identity($1,$2,$3::jsonb) v',[room,action,JSON.stringify(payload)])}
const a=await as(0,"select public.party_save_slot('create',1,null,'原有战士','战士') v");
assert.equal(a.players[0].race,null);
const b=await as(1,'select public.party_command($1,$2,$3::jsonb) v',[a.room,'join',JSON.stringify({name:'龙裔法师',class:'法师'})]);
assert.equal(b.players.find(p=>p.id===b.me).race,null);
const picked=await cmd(0,a.room,'race',{race:'矮人'});
assert.equal(picked.players.find(p=>p.id===picked.me).race,'矮人');
assert.equal(picked.players.find(p=>p.id===picked.me).max_hp,a.players.find(p=>p.id===a.me).max_hp+3);
await assert.rejects(cmd(0,a.room,'race',{race:'精灵'}),/RACE_ALREADY_CHOSEN/);
await assert.rejects(cmd(1,a.room,'race',{race:'龙裔',ancestry:'虚空'}),/INVALID_RACE/);
let dragon=await cmd(1,a.room,'race',{race:'龙裔',ancestry:'闪电'});
assert.equal(dragon.players.find(p=>p.id===dragon.me).ancestry,'闪电');
assert.equal((await as(0,'select public.party_v31_slots() v'))[0].room,a.room);
await assert.rejects(cmd(1,a.room,'check',{skill:'瞎编',dc:15}),/INVALID_SKILL/);
await assert.rejects(cmd(1,a.room,'check',{skill:'奥秘',dc:99}),/INVALID_DC_OR_BONUS/);
dragon=await cmd(1,a.room,'check',{skill:'奥秘',dc:15,mode:'advantage'});
assert.equal(dragon.state.last_roll.mode,'advantage');
assert.equal(dragon.state.last_roll.dice.length,2);
assert.equal(dragon.state.last_roll.proficiency,2);
assert.equal(dragon.state.last_roll.total,dragon.state.last_roll.d20+dragon.state.last_roll.attribute+dragon.state.last_roll.proficiency+dragon.state.last_roll.other);
const dwarf=await cmd(0,a.room,'check',{skill:'体质',dc:12,save:true});
assert.equal(dwarf.state.last_roll.save,true);
async function world(i,action,payload={}){return as(i,'select public.party_v4_world($1,$2,$3::jsonb) v',[a.room,action,JSON.stringify(payload)])}
await db.query('update public.players set level=4 where id=$1',[a.me]);
const leveled=await as(0,'select public.party_snapshot($1) v',[a.room]);
assert.equal(leveled.players.find(p=>p.id===a.me).build.points,1);
await world(0,'build',{choice:'强韧'});
assert.equal((await as(0,'select public.party_snapshot($1) v',[a.room])).players.find(p=>p.id===a.me).build.feats[0],'强韧');
await assert.rejects(world(0,'build',{choice:'武器大师'}),/NO_BUILD_POINTS/);
await as(0,'select public.party_command($1,$2,$3::jsonb) v',[a.room,'ready','{}']);
await as(1,'select public.party_command($1,$2,$3::jsonb) v',[a.room,'ready','{}']);
await as(0,'select public.party_command($1,$2,$3::jsonb) v',[a.room,'start','{}']);
await world(0,'camp_enter');
assert.equal((await world(0,'short_rest')).state.v4_short_chapter,0);
await assert.rejects(world(0,'short_rest'),/SHORT_REST_USED/);
await world(0,'long_rest');
await assert.rejects(world(1,'long_rest'),/REST_UNAVAILABLE/);
await world(0,'camp_leave');
await as(0,'select public.party_region($1,$2) v',[a.room,'wonders']);
await assert.rejects(as(1,'select public.party_v4_dialogue($1,$2) v',[a.room,'elric_dwarf']),/ROUTE_REQUIREMENT/);
const branch=await as(0,'select public.party_v4_dialogue($1,$2) v',[a.room,'elric_dwarf']);
assert.equal(branch.state.last_roll.skill,'调查');
assert.ok(branch.state.v4_dialogue_attempts[`${a.me}:elric_dwarf`]);
await assert.rejects(as(0,'select public.party_v4_dialogue($1,$2) v',[a.room,'elric_dwarf']),/ROUTE_RESOLVED|ROUTE_ATTEMPTED/);
await as(0,'select public.party_region($1,$2) v',[a.room,'city']);
await db.query('update public.game_states set state=jsonb_set(state,\'{combat}\', $2::jsonb) where room_code=$1',[a.room,JSON.stringify({name:'种族能力试炼',enemies:[{name:'假人一',hp:60,max_hp:60,ac:10,attack_bonus:1,damage_min:1,damage_die:4},{name:'假人二',hp:60,max_hp:60,ac:10,attack_bonus:1,damage_min:1,damage_die:4}],hp:120,max_hp:120,turn:b.me,initiative:[{id:b.me,roll:20},{id:a.me,roll:10}],round:1,wards:{}})]);
const breath=await as(1,'select public.party_v4_racial($1,$2,$3) v',[a.room,'breath',0]);
assert.ok(breath.state.combat.enemies.every(enemy=>enemy.hp<enemy.max_hp));
assert.equal(breath.state.combat.racial_uses[b.me],true);
await assert.rejects(as(1,'select public.party_v4_racial($1,$2,$3) v',[a.room,'breath',0]),/RACIAL_ABILITY_USED|NOT_YOUR_TURN/);
await db.query('update public.game_states set state=jsonb_set(state,\'{combat}\',\'null\'::jsonb) where room_code=$1',[a.room]);
const crime=await world(1,'crime',{type:'theft'});
assert.ok(['caught','unseen'].includes(crime.state.v4_crimes[`${b.me}:0:city:theft`]));
await assert.rejects(world(1,'crime',{type:'theft'}),/CRIME_ALREADY_ATTEMPTED/);
await db.query('update public.players set wanted=2 where id=$1',[b.me]);
await world(1,'guard',{choice:'接受逮捕'});
assert.equal((await as(1,'select public.party_snapshot($1) v',[a.room])).players.find(p=>p.id===b.me).conditions.jailed,true);
await world(1,'prison',{choice:'服刑'});
assert.equal((await as(1,'select public.party_snapshot($1) v',[a.room])).players.find(p=>p.id===b.me).wanted,0);
const finaleCombat={name:'议会雇佣兵首领',enemies:[{name:'佣兵首领',hp:55,max_hp:55,ac:17,attack_bonus:5,damage_min:4,damage_die:6},{name:'铁甲佣兵',hp:22,max_hp:22,ac:15,attack_bonus:4,damage_min:2,damage_die:6}],hp:77,max_hp:77,turn:a.me,initiative:[{id:a.me,roll:20},{id:b.me,roll:10}],round:1,environment:[]};
await db.query('update public.game_states set state=state||jsonb_build_object(\'chapter\',28,\'combat\',$2::jsonb) where room_code=$1',[a.room,JSON.stringify(finaleCombat)]);
let finalState=await as(0,'select public.party_snapshot($1) v',[a.room]);
assert.equal(finalState.state.combat.final_phase,1);
let staged={...finalState.state.combat,enemies:finalState.state.combat.enemies.map((e,i)=>i===0?{...e,hp:1}:e)};
staged.hp=staged.enemies.reduce((sum,e)=>sum+e.hp,0);
let phase=await as(0,'select public.campaign_finish_turn($1,$2::jsonb,$3) v',[a.room,JSON.stringify(staged),a.me]);
assert.equal(phase.combat.final_phase,2);
assert.ok(phase.combat.enemies.some(e=>e.name==='钟厅增援弩手'));
staged={...phase.combat,enemies:phase.combat.enemies.map((e,i)=>i===0?{...e,hp:1}:e)};
staged.hp=staged.enemies.reduce((sum,e)=>sum+e.hp,0);
phase=await as(0,'select public.campaign_finish_turn($1,$2::jsonb,$3) v',[a.room,JSON.stringify(staged),a.me]);
assert.equal(phase.combat.final_phase,3);
assert.ok(phase.combat.enemies.some(e=>e.name==='誓死焚证者'));
await db.query('update public.game_states set state=jsonb_set(state,\'{combat}\', $2::jsonb) where room_code=$1',[a.room,JSON.stringify(phase.combat)]);
assert.equal((await as(0,'select public.party_snapshot($1) v',[a.room])).state.final_victory,undefined);
await db.query('update public.game_states set state=jsonb_set(state,\'{combat,hp}\',\'0\'::jsonb) where room_code=$1',[a.room]);
assert.ok((await as(0,'select public.party_snapshot($1) v',[a.room])).state.final_victory);
await db.query("update public.game_states set state=jsonb_set(jsonb_set(state,'{side_quests}','{}'::jsonb,true),'{side_quests,hearth}', '{\"status\":\"已完成\",\"outcome\":\"invite\"}'::jsonb,true) where room_code=$1",[a.room]);
const recruited=await as(0,'select public.party_snapshot($1) v',[a.room]);
assert.equal(recruited.players.find(p=>p.name==='亚岚·铜脉')?.race,'矮人');
assert.ok(recruited.state.v4_aran_joined);
assert.equal(recruited.players.find(p=>p.id===a.me).reputation.gond,12);
await world(0,'camp_enter');
await db.query('update public.players set inventory=inventory||\'"炉心护符"\'::jsonb where id=$1',[a.me]);
const equipped=await world(0,'companion_equip',{companion:recruited.state.v4_aran_joined,item:'炉心护符'});
assert.ok(equipped.players.find(p=>p.name==='亚岚·铜脉').equipment.includes('炉心护符'));
await world(0,'camp_leave');
await db.query("update public.game_states set state=jsonb_set(state,'{version}', '44'::jsonb) where room_code=$1",[a.room]);
assert.equal((await as(0,'select public.party_snapshot($1) v',[a.room])).players.filter(p=>p.name==='亚岚·铜脉').length,1);
const aran=recruited.players.find(p=>p.name==='亚岚·铜脉');
await db.query("update public.game_states set state=state||jsonb_build_object('chapter',0,'combat',$2::jsonb) where room_code=$1",[a.room,JSON.stringify({name:'伙伴试炼',enemies:[{name:'木偶',hp:70,max_hp:70,ac:9,attack_bonus:0,damage_min:1,damage_die:3}],hp:70,max_hp:70,turn:aran.id,initiative:[{id:aran.id,roll:20},{id:a.me,roll:10}],round:1,wards:{}})]);
const acted=await as(0,'select public.party_v4_companion($1,$2,$3,$4) v',[a.room,aran.id,'shock',-1]);
assert.ok(acted.state.combat.enemies[0].hp<acted.state.combat.enemies[0].max_hp);
assert.equal(acted.players.find(p=>p.id===aran.id).ability_charges,1);
await as(0,"select public.party_save_slot('save',1) v");
const restored=await as(0,'select public.party_enter_slot(1) v');
assert.equal(restored.players.find(p=>p.id===aran.id)?.race,'矮人');
assert.equal(restored.players.find(p=>p.id===b.me)?.ancestry,'闪电');
assert.equal(restored.state.side_quests.hearth.status,'已完成');
assert.equal((await db.query('select saved_players from public.save_slots where room_code=$1',[a.room])).rows[0].saved_players.find(p=>p.id===aran.id).race,'矮人');
const hazardRoom=await as(0,"select public.party_save_slot('create',2,null,'环境测试者','战士') v");
await db.query("update public.game_states set state=state||jsonb_build_object('chapter',28,'combat',$2::jsonb) where room_code=$1",[hazardRoom.room,JSON.stringify(finaleCombat)]);
await db.query("update public.game_states set state=jsonb_set(jsonb_set(state,'{combat,hp}','0'::jsonb),'{combat,enemies}',(select jsonb_agg(jsonb_set(e,'{hp}','0'::jsonb)) from jsonb_array_elements(state#>'{combat,enemies}') e)) where room_code=$1",[hazardRoom.room]);
const hazardState=await as(0,'select public.party_snapshot($1) v',[hazardRoom.room]);
assert.equal(hazardState.state.combat.final_phase,2);
assert.equal(hazardState.state.final_victory,undefined);
await as(1,'select public.party_command($1,$2,$3::jsonb) v',[a.room,'leave','{}']);
await assert.rejects(cmd(1,a.room,'check',{skill:'奥秘',dc:15}),/RECONNECT_FIRST/);
console.log('V4.0 FOUNDATION PASS: old save, race, D20, build, camp rest, crime/prison and online-only actions');
