-- Apply in Supabase SQL editor after reviewing the project. Enable anonymous sign-ins in Auth first.
create extension if not exists pgcrypto;
create table if not exists public.rooms (code text primary key, title text not null default 'Upper City 30H', created_at timestamptz not null default now());
create table if not exists public.players (id bigint generated by default as identity primary key, room_code text not null references public.rooms(code) on delete cascade, name text not null, class_name text, last_seen timestamptz default now(), created_at timestamptz not null default now());
create table if not exists public.game_states (room_code text primary key references public.rooms(code) on delete cascade, state jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.messages (id bigint generated by default as identity primary key, room_code text not null references public.rooms(code) on delete cascade, sender text not null, body text not null, kind text not null default 'action', created_at timestamptz not null default now());
alter table public.players add column if not exists user_id uuid;
alter table public.players add column if not exists is_host boolean not null default false;
alter table public.players add column if not exists is_ready boolean not null default false;
alter table public.players add column if not exists hp integer not null default 10;
alter table public.players add column if not exists max_hp integer not null default 10;
alter table public.players add column if not exists ac integer not null default 12;
alter table public.players add column if not exists stats jsonb not null default '[10,10,10,10,10,10]'::jsonb;
alter table public.players add column if not exists inventory jsonb not null default '["治疗药水"]'::jsonb;
alter table public.players add column if not exists equipment jsonb not null default '["基础武器"]'::jsonb;
alter table public.players add column if not exists gold integer not null default 15;
alter table public.players add column if not exists death_failures integer not null default 0;
alter table public.players add column if not exists death_successes integer not null default 0;
create unique index if not exists players_room_user_uq on public.players(room_code,user_id);
alter table public.rooms enable row level security;
alter table public.players enable row level security;
alter table public.game_states enable row level security;
alter table public.messages enable row level security;
drop policy if exists "rooms public demo" on public.rooms;
drop policy if exists "players public demo" on public.players;
drop policy if exists "game_states public demo" on public.game_states;
drop policy if exists "messages public demo" on public.messages;
-- Access reads through one security-definer snapshot RPC. No direct table operations are granted.
revoke all on public.rooms,public.players,public.game_states,public.messages from anon,authenticated;
create table if not exists public.campaign_chapters (id integer primary key, choices jsonb not null);
revoke all on public.campaign_chapters from anon,authenticated;
insert into public.campaign_chapters(id,choices) values (0,'[{"label":"调查灰烬","clue":"询问守门人","flag":"ash"},{"label":"混入马车队","flag":"gate"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (1,'[{"label":"打开铜匣","clue":"铜匣密码","flag":"cipher"},{"label":"保护掌柜","flag":"keeper"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (2,'[{"label":"破译灯语","clue":"隐秘会面","flag":"signal"},{"label":"追上信使","flag":"courier"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (3,'[{"label":"核对座次","clue":"缺席的主人","flag":"absence"},{"label":"安抚宾客","flag":"trust"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (4,'[{"label":"带走地图","clue":"地契地图","flag":"map"},{"label":"留下假地图","flag":"decoy"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (5,'[{"label":"抄录账本","clue":"灰市账目","flag":"ledger"},{"label":"答应保护工人","flag":"workers"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (6,'[{"label":"分析蕨叶","clue":"矿坑孢子","flag":"spore"},{"label":"向园丁许诺帮助","flag":"gardener"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (7,'[{"label":"比对笔迹","clue":"篡改的信","flag":"letters"},{"label":"公开其中一封","flag":"publicity"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (8,'[{"label":"接受调查","clue":"巡逻证词","flag":"patrol"},{"label":"以金币换消息","flag":"bribe"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (9,'[{"label":"拓印印章","clue":"议会印记","flag":"seal"},{"label":"向街坊说明","flag":"neighbours"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (10,'[{"label":"潜入拍卖","clue":"拍卖名单","flag":"auction"},{"label":"与买家交涉","flag":"buyer"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (11,'[{"label":"拆解齿轮","clue":"齿轮暗格","flag":"gear"},{"label":"安抚守塔人","flag":"warden"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (12,'[{"label":"修复目录","clue":"旧城选票","flag":"ballots"},{"label":"承诺开放档案","flag":"archive"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (13,'[{"label":"追踪白鸦","clue":"信使路线","flag":"raven"},{"label":"营救驯养人","flag":"handler"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (14,'[{"label":"核对年代","clue":"错位日期","flag":"dates"},{"label":"公布矛盾","flag":"expose"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (15,'[{"label":"分享经历","clue":"无名者口述","flag":"testimony"},{"label":"带药给居民","flag":"medicine"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (16,'[{"label":"搜查哨站","clue":"炼金徽章","flag":"alchemist"},{"label":"救助伤者","flag":"rescued"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (17,'[{"label":"备战","clue":"甲壳残片","flag":"shell"},{"label":"寻找绕行路线","flag":"bypass"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (18,'[{"label":"保护证人","clue":"驱逐案卷","flag":"verdict"},{"label":"交换护卫承诺","flag":"witness"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (19,'[{"label":"质询议员","clue":"议员供词","flag":"confession"},{"label":"给予作证机会","flag":"mercy"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (20,'[{"label":"封锁长廊","clue":"镜厅脚印","flag":"mirror"},{"label":"保护证人","flag":"protected"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (21,'[{"label":"潜入办公室","clue":"停钟命令","flag":"order"},{"label":"接触改革派","flag":"reform"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (22,'[{"label":"尝试谈判","clue":"封桥令","flag":"bridge"},{"label":"请求旧盟友","flag":"allies"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (23,'[{"label":"组织守卫","clue":"纵火工具","flag":"arson"},{"label":"先救馆员","flag":"librarians"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (24,'[{"label":"收集意见","clue":"各派条件","flag":"factions"},{"label":"举行公开集会","flag":"assembly"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (25,'[{"label":"鉴定契约","clue":"原始契约","flag":"contract"},{"label":"邀请所有派系","flag":"unity"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (26,'[{"label":"展示证据","clue":"矛盾命令","flag":"guard"},{"label":"争取守卫","flag":"defector"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (27,'[{"label":"迎战","clue":"雇佣契约","flag":"mercenary"},{"label":"疏散市民","flag":"civilians"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (28,'[{"label":"恢复公民议会","clue":"公民议会","flag":"council"},{"label":"建立地下自治","flag":"autonomy"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;
insert into public.campaign_chapters(id,choices) values (29,'[{"label":"记录后日谈","clue":"队伍编年史","flag":"epilogue"},{"label":"继续探索","flag":"legacy"}]'::jsonb) on conflict(id) do update set choices=excluded.choices;

create or replace function public.party_snapshot(p_code text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
 if auth.uid() is null or not exists(select 1 from public.players where room_code=upper(p_code) and user_id=auth.uid()) then raise exception 'NOT_MEMBER'; end if;
 select jsonb_build_object('room',r.code,'players',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'class_name',p.class_name,'is_host',p.is_host,'is_ready',p.is_ready,'hp',p.hp,'max_hp',p.max_hp,'ac',p.ac,'stats',p.stats,'inventory',p.inventory,'equipment',p.equipment,'gold',p.gold,'death_failures',p.death_failures,'death_successes',p.death_successes,'last_seen',p.last_seen) order by p.created_at) from public.players p where p.room_code=r.code and p.user_id is not null),'[]'::jsonb),'me',(select p.id from public.players p where p.room_code=r.code and p.user_id=auth.uid()),'state',coalesce(g.state,'{}'::jsonb),'messages',coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from (select id,sender,body,kind,created_at from public.messages where room_code=r.code order by id desc limit 100) m),'[]'::jsonb)) into result from public.rooms r left join public.game_states g on g.room_code=r.code where r.code=upper(p_code);
 return result;
end $$;
create or replace function public.party_command(p_code text, p_action text, p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_name text; v_class text; v_id bigint; v_host boolean; v_state jsonb; v_players int; v_unready int; v_target bigint; v_roll int; v_bonus int; v_dc int; v_dmg int; v_hp int; v_ac int; v_idx int; v_flags jsonb; v_clues jsonb; v_combat jsonb; v_turn bigint; v_next bigint; v_enemy_hp int; v_log text; v_chars text:='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; v_rand bytea; v_try int; v_newcode text; v_stats jsonb; v_max int; v_init jsonb; v_ord bigint;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 if p_action='create' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人') then raise exception 'INVALID_CHARACTER'; end if;
  for v_try in 1..10 loop
   v_rand:=decode(replace(gen_random_uuid()::text,'-',''),'hex'); v_newcode:='';
   for v_idx in 0..4 loop v_newcode:=v_newcode||substr(v_chars,1+get_byte(v_rand,v_idx)%length(v_chars),1); end loop;
   insert into public.rooms(code) values(v_newcode) on conflict do nothing;
   exit when found;
  end loop;
  if v_try=10 and not found then raise exception 'CODE_EXHAUSTED'; end if;
  v_code:=v_newcode;
  perform public.party_character(v_code,v_uid,v_name,v_class,true);
  insert into public.game_states(room_code,state) values(v_code,jsonb_build_object('started',false,'chapter',0,'flags','[]'::jsonb,'clues','[]'::jsonb,'quest','追查消失的议员','completed_quests','[]'::jsonb,'combat',null,'version',1,'ending',null));
  return public.party_snapshot(v_code);
 end if;
 if p_action='join' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人') then raise exception 'INVALID_CHARACTER'; end if;
  perform 1 from public.rooms where code=v_code for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if exists(select 1 from public.game_states where room_code=v_code and (state->>'started')::boolean) then raise exception 'GAME_STARTED'; end if;
  if exists(select 1 from public.players where room_code=v_code and user_id=v_uid) then return public.party_snapshot(v_code); end if;
  select count(*) into v_players from public.players where room_code=v_code and user_id is not null;
  if v_players>=5 then raise exception 'ROOM_FULL'; end if;
  perform public.party_character(v_code,v_uid,v_name,v_class,false);
  return public.party_snapshot(v_code);
 end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select id,name,is_host,hp,ac into v_id,v_name,v_host,v_hp,v_ac from public.players where room_code=v_code and user_id=v_uid;
 if v_id is null then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if p_action='heartbeat' then update public.players set last_seen=now() where id=v_id; return public.party_snapshot(v_code); end if;
 if p_action='leave' then
  delete from public.players where id=v_id;
  if v_host then update public.players set is_host=true,is_ready=false where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1); end if;
  return jsonb_build_object('left',true);
 end if;
 if p_action='claim_host' then
  if not exists(select 1 from public.players where room_code=v_code and is_host and user_id is not null and last_seen>now()-interval '5 minutes') then
   update public.players set is_host=false where room_code=v_code;
   update public.players set is_host=true where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1);
  end if;
  return public.party_snapshot(v_code);
 end if;
 if p_action='ready' then
  if (v_state->>'started')::boolean then raise exception 'ALREADY_STARTED'; end if;
  update public.players set is_ready=not is_ready where id=v_id;
 elsif p_action='start' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  select count(*),count(*) filter(where not is_ready) into v_players,v_unready from public.players where room_code=v_code and user_id is not null;
  if v_players<2 or v_players>5 or v_unready>0 then raise exception 'PARTY_NOT_READY'; end if;
  v_state:=jsonb_set(v_state,'{started}','true'::jsonb);
  v_log:='冒险开始。';
 elsif p_action='chat' then
  v_log:=left(trim(coalesce(p_payload->>'body','')),500);
  if length(v_log)<1 then raise exception 'EMPTY_MESSAGE'; end if;
 elsif p_action='roll' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  -- The browser chooses a skill and DC; the modifier comes from the authenticated character.
  if p_payload->>'skill' not in ('调查','洞悉','说服','潜行','运动','奥秘','求生') then raise exception 'INVALID_SKILL'; end if;
  select floor(((stats->>case p_payload->>'skill' when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 else 5 end)::int-10)/2.0)::int
    + case when (class_name='战士' and p_payload->>'skill'='运动') or (class_name='游荡者' and p_payload->>'skill' in ('调查','潜行')) or (class_name='法师' and p_payload->>'skill'='奥秘') or (class_name='牧师' and p_payload->>'skill'='洞悉') or (class_name='游侠' and p_payload->>'skill'='求生') or (class_name='吟游诗人' and p_payload->>'skill'='说服') then 2 else 0 end into v_bonus from public.players where id=v_id;
  v_dc:=greatest(5,least(30,coalesce((p_payload->>'dc')::int,15)));
  v_roll:=floor(random()*20)::int+1;
  v_log:=left(coalesce(p_payload->>'skill','技能'),30)||'检定 D20='||v_roll||'，加值 '||v_bonus||'，DC '||v_dc||'：'||case when v_roll=20 then '大成功' when v_roll=1 then '大失败' when v_roll+v_bonus>=v_dc then '成功' else '失败' end;
 elsif p_action='choice' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)=(v_state->>'chapter')::int then raise exception 'CHOICE_ALREADY_MADE'; end if;
  v_idx:=coalesce((p_payload->>'index')::int,-1);
  if v_idx<0 or v_idx>1 then raise exception 'INVALID_CHOICE'; end if;
  select choices->v_idx into p_payload from public.campaign_chapters where id=(v_state->>'chapter')::int;
  if p_payload is null then raise exception 'INVALID_CHOICE'; end if;
  v_flags:=coalesce(v_state->'flags','[]'::jsonb); v_clues:=coalesce(v_state->'clues','[]'::jsonb);
  if length(coalesce(p_payload->>'flag',''))>0 and not v_flags ? (p_payload->>'flag') then v_flags:=v_flags||to_jsonb(left(p_payload->>'flag',40)); end if;
  if length(coalesce(p_payload->>'clue',''))>0 and not v_clues ? (p_payload->>'clue') then v_clues:=v_clues||to_jsonb(left(p_payload->>'clue',60)); end if;
  v_state:=jsonb_set(jsonb_set(v_state,'{flags}',v_flags),'{clues}',v_clues);
  v_state:=jsonb_set(v_state,'{chosen_chapter}',to_jsonb((v_state->>'chapter')::int));
  v_log:='选择：'||left(coalesce(p_payload->>'label',''),80);
 elsif p_action='advance' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)<>coalesce((v_state->>'chapter')::int,0) then raise exception 'CHOOSE_BEFORE_ADVANCE'; end if;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and coalesce((v_state#>>'{combat,hp}')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
  v_idx:=least(29,coalesce((v_state->>'chapter')::int,0)+1);
  v_state:=jsonb_set(jsonb_set(v_state,'{chapter}',to_jsonb(v_idx)),'{completed_quests}',coalesce(v_state->'completed_quests','[]'::jsonb)||to_jsonb(v_idx-1));
  if v_idx in (17,28) then
   v_enemy_hp:=case when v_idx=17 then 35 else 55 end;
   select jsonb_agg(jsonb_build_object('id',id,'roll',roll) order by roll desc,id),(array_agg(id order by roll desc,id))[1] into v_init,v_turn from (select id,floor(random()*20)::int+1 as roll from public.players where room_code=v_code and user_id is not null and hp>0) i;
   v_state:=jsonb_set(v_state,'{combat}',jsonb_build_object('name',case when v_idx=17 then '盐井甲壳兽' else '议会雇佣兵首领' end,'hp',v_enemy_hp,'max_hp',v_enemy_hp,'ac',13,'turn',v_turn,'initiative',v_init,'round',1));
  else v_state:=jsonb_set(v_state,'{combat}','null'::jsonb); end if;
  if v_idx=29 then v_state:=jsonb_set(v_state,'{ending}',to_jsonb(case when (v_state->'flags') ? 'council' then '公民议会重建' when (v_state->'flags') ? 'autonomy' then '地下自治联盟' when jsonb_array_length(v_state->'flags')>=18 then '城市共同体' else '艰难的黎明' end)); end if;
  if v_idx%5=0 then update public.players set gold=gold+10 where room_code=v_code and user_id is not null; end if;
  v_log:='推进至第 '||(v_idx+1)||' 章。'||case when v_idx%5=0 then ' 队员各获 10 金币。' else '' end;
 elsif p_action='attack' then
  v_combat:=v_state->'combat';
  if v_combat is null or v_combat='null'::jsonb or (v_combat->>'hp')::int<=0 then raise exception 'NO_COMBAT'; end if;
  if (v_combat->>'turn')::bigint<>v_id then raise exception 'NOT_YOUR_TURN'; end if;
  if v_hp<=0 then raise exception 'DOWNED'; end if;
  select case class_name when '战士' then 5 when '游荡者' then 5 when '法师' then 5 when '游侠' then 5 else 4 end into v_bonus from public.players where id=v_id;
  v_roll:=floor(random()*20)::int+1; v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_combat->>'ac')::int) then 0 else (floor(random()*8)::int+1)+v_bonus+case when v_roll=20 then (floor(random()*8)::int+1) else 0 end end;
  v_enemy_hp:=greatest(0,(v_combat->>'hp')::int-v_dmg); v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(v_enemy_hp));
  v_log:='攻击 D20='||v_roll||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'，伤害 '||v_dmg;
  if v_enemy_hp>0 then
   select ord into v_ord from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) where (item->>'id')::bigint=v_id;
   select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where e.ord>v_ord and p.hp>0 order by e.ord limit 1;
   if v_next is null then
    -- The enemy acts once after the party round.
    v_roll:=floor(random()*20)::int+1;
    if v_roll=20 or (v_roll<>1 and v_roll+4>=v_ac) then
     v_dmg:=floor(random()*6)::int+3;
     update public.players set hp=greatest(0,hp-v_dmg) where id=v_id;
     v_log:=v_log||'；敌人反击 '||v_name||'，伤害 '||v_dmg;
    else v_log:=v_log||'；敌人反击未命中'; end if;
    select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where p.hp>0 order by e.ord limit 1;
    v_combat:=jsonb_set(v_combat,'{round}',to_jsonb((v_combat->>'round')::int+1));
   end if;
   if v_next is null then v_log:=v_log||'；队伍全员倒地'; end if;
   v_combat:=jsonb_set(v_combat,'{turn}',coalesce(to_jsonb(v_next),'null'::jsonb));
  else v_log:=v_log||'；敌人倒下'; end if;
  v_state:=jsonb_set(v_state,'{combat}',v_combat);
 elsif p_action='heal' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_target:=coalesce((p_payload->>'target')::bigint,v_id);
  if not exists(select 1 from public.players where id=v_target and room_code=v_code and user_id is not null) then raise exception 'INVALID_TARGET'; end if;
  if not (select inventory ? '治疗药水' from public.players where id=v_id) then raise exception 'NO_POTION'; end if;
  update public.players set inventory=inventory-'治疗药水' where id=v_id;
  update public.players set hp=least(max_hp,hp+8),death_failures=0,death_successes=0 where id=v_target and hp>=0;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_target)); end if;
  v_log:='使用治疗药水，恢复 8 HP。';
 elsif p_action='buy' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if p_payload->>'item'='治疗药水' then
   update public.players set gold=gold-10,inventory=inventory||'"治疗药水"'::jsonb where id=v_id and gold>=10;
   if not found then raise exception 'NOT_ENOUGH_GOLD'; end if;
   v_log:='购买治疗药水，花费 10 金币。';
  elsif p_payload->>'item'='盾牌' then
   if (select inventory ? '盾牌' or equipment ? '盾牌' from public.players where id=v_id) then raise exception 'ALREADY_OWNED'; end if;
   update public.players set gold=gold-30,inventory=inventory||'"盾牌"'::jsonb where id=v_id and gold>=30;
   if not found then raise exception 'NOT_ENOUGH_GOLD'; end if;
   v_log:='购买盾牌，花费 30 金币。';
  else raise exception 'UNKNOWN_ITEM'; end if;
 elsif p_action='equip' then
  if p_payload->>'item'<>'盾牌' or not (select inventory ? '盾牌' from public.players where id=v_id) then raise exception 'ITEM_NOT_IN_BAG'; end if;
  update public.players set inventory=inventory-'盾牌',equipment=equipment||'"盾牌"'::jsonb,ac=ac+1 where id=v_id;
  v_log:='装备盾牌，AC +1。';
 elsif p_action='death_save' then
  if v_hp<>0 then raise exception 'NOT_DOWNED'; end if;
  v_roll:=floor(random()*20)::int+1;
  if v_roll=20 then update public.players set hp=1,death_failures=0,death_successes=0 where id=v_id;
   if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_id)); end if;
  elsif v_roll=1 then update public.players set death_failures=least(3,death_failures+2) where id=v_id;
  elsif v_roll>=10 then update public.players set death_successes=least(3,death_successes+1) where id=v_id;
  else update public.players set death_failures=least(3,death_failures+1) where id=v_id; end if;
  v_log:='死亡豁免 D20='||v_roll||case when v_roll=20 then '，恢复 1 HP' else '' end;
 else raise exception 'UNKNOWN_ACTION'; end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 if v_log is not null then insert into public.messages(room_code,sender,body,kind) values(v_code,v_name,v_log,p_action); end if;
 return public.party_snapshot(v_code);
end $$;
create or replace function public.party_character(p_code text,p_uid uuid,p_name text,p_class text,p_host boolean) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_stats jsonb; v_hp int; v_ac int;
begin
 if p_uid<>auth.uid() then raise exception 'INVALID_IDENTITY'; end if;
 if exists(select 1 from public.players where room_code=p_code and name=p_name) then raise exception 'NAME_TAKEN'; end if;
 v_stats:=case p_class when '战士' then '[16,12,14,10,10,10]' when '游荡者' then '[10,16,12,12,10,12]' when '法师' then '[8,12,12,16,12,10]' when '牧师' then '[12,10,14,10,16,12]' when '游侠' then '[12,16,12,12,14,10]' else '[10,14,12,12,10,16]' end::jsonb;
 v_hp:=case p_class when '战士' then 14 when '法师' then 8 when '牧师' then 11 when '游侠' then 11 else 10 end;
 v_ac:=case p_class when '战士' then 16 when '牧师' then 15 when '游侠' then 14 when '游荡者' then 14 when '吟游诗人' then 13 else 12 end;
 insert into public.players(room_code,user_id,name,class_name,is_host,hp,max_hp,ac,stats) values(p_code,p_uid,p_name,p_class,p_host,v_hp,v_hp,v_ac,v_stats);
end $$;
revoke all on function public.party_character(text,uuid,text,text,boolean) from public,anon,authenticated;
revoke all on function public.party_command(text,text,jsonb) from public,anon;
revoke all on function public.party_snapshot(text) from public,anon;
grant execute on function public.party_command(text,text,jsonb),public.party_snapshot(text) to authenticated;
-- Broadcast only a generic room change signal; read current state through authenticated snapshot.
create or replace function public.party_notify() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin perform pg_notify('party_change',coalesce(new.room_code,old.room_code)); return coalesce(new,old); end $$;
-- Postgres Changes requires SELECT RLS: members can read only their room. Direct writes stay revoked.
create or replace function public.is_party_member(p_code text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.players where room_code=p_code and user_id=auth.uid()) $$;
revoke all on function public.is_party_member(text) from public,anon;
grant execute on function public.is_party_member(text) to authenticated;
drop policy if exists "room member read" on public.rooms;
create policy "room member read" on public.rooms for select to authenticated using (public.is_party_member(code));
drop policy if exists "player member read" on public.players;
create policy "player member read" on public.players for select to authenticated using (public.is_party_member(players.room_code));
drop policy if exists "state member read" on public.game_states;
create policy "state member read" on public.game_states for select to authenticated using (public.is_party_member(game_states.room_code));
drop policy if exists "message member read" on public.messages;
create policy "message member read" on public.messages for select to authenticated using (public.is_party_member(messages.room_code));
grant select on public.rooms,public.players,public.game_states,public.messages to authenticated;
do $$ begin alter publication supabase_realtime add table public.players; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.game_states; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end $$;
