-- Generated by npm run powers:sql. The JS catalog and this migration must be deployed together.
alter table public.players add column if not exists level integer not null default 1;
alter table public.players add column if not exists spell_slots jsonb not null default '[0,2,0,0,0,0,0]'::jsonb;
alter table public.players add column if not exists ability_charges integer not null default 2;
create table if not exists public.campaign_powers (id text primary key,profession text not null,ring integer not null check(ring between 0 and 6),kind text not null,amount integer not null,name text not null,description text not null);
alter table public.campaign_powers enable row level security;
revoke all on public.campaign_powers from public,anon,authenticated;
insert into public.campaign_powers(id,profession,ring,kind,amount,name,description) values
('fighter_strike','战士','0','damage','12','破阵斩','强力近战攻击。'),
('fighter_wind','战士','0','heal','7','坚韧复起','恢复自己或队友的生命。'),
('rogue_sneak','游荡者','0','damage','13','背刺','趁破绽造成高额伤害。'),
('rogue_smoke','游荡者','0','ward','3','烟幕闪避','抵挡下一次敌人攻击。'),
('wizard_bolt','法师','0','damage','9','奥术飞矢','基础奥术攻击。'),
('wizard_focus','法师','0','ward','2','秘法护罩','保护一名队员。'),
('cleric_light','牧师','0','damage','9','辉光打击','以神圣光芒攻击。'),
('cleric_prayer','牧师','0','heal','8','祈祷','治疗一名队员。'),
('ranger_arrow','游侠','0','damage','11','追踪箭','瞄准敌人的行踪。'),
('ranger_herbs','游侠','0','heal','7','野外草药','治疗一名队员。'),
('bard_note','吟游诗人','0','damage','9','裂音','用共鸣打乱敌人。'),
('bard_inspire','吟游诗人','0','ward','3','鼓舞','保护一名队员。'),
('paladin_smite','圣武士','0','damage','11','誓约重击','用神圣武器攻击。'),
('paladin_hands','圣武士','0','heal','9','圣疗','触碰并治疗一名队员。'),
('wizard_1','法师','1','damage','11','星火','引燃凝聚的星尘。'),
('wizard_2','法师','2','ward','4','镜面屏障','折射下一次袭击。'),
('wizard_3','法师','3','damage','19','雷霆弧','闪电贯穿敌人的防线。'),
('wizard_4','法师','4','weaken','2','重力扭曲','降低敌人的护甲和攻击。'),
('wizard_5','法师','5','damage','30','坠星','召来一颗炽热陨星。'),
('wizard_6','法师','6','damage','38','流星破城','释放强大的星陨冲击。'),
('cleric_1','牧师','1','heal','12','晨光疗愈','恢复队员生命。'),
('cleric_2','牧师','2','damage','16','净焰','焚除敌人的邪祟。'),
('cleric_3','牧师','3','heal','23','生命圣言','大幅恢复一名队员。'),
('cleric_4','牧师','4','ward','5','庇佑圣域','保护队员免受袭击。'),
('cleric_5','牧师','5','damage','29','审判之光','凝聚烈光打击敌人。'),
('cleric_6','牧师','6','heal','40','黎明复苏','救回重伤的队员。'),
('ranger_1','游侠','1','damage','12','荆棘箭','带刺箭矢追踪目标。'),
('ranger_2','游侠','2','weaken','1','困兽藤','缠住敌人，削弱防御。'),
('ranger_3','游侠','3','damage','21','猎鹰齐射','连续射出锐利箭矢。'),
('ranger_4','游侠','4','heal','25','森林复苏','唤醒自然生机。'),
('ranger_5','游侠','5','damage','31','风暴猎杀','箭雨随风暴落下。'),
('ranger_6','游侠','6','damage','39','星野追猎','向敌人的命运轨迹射击。'),
('bard_1','吟游诗人','1','damage','11','刺耳和弦','震动敌人的心神。'),
('bard_2','吟游诗人','2','heal','16','安魂曲','以旋律恢复队员生命。'),
('bard_3','吟游诗人','3','weaken','1','揭幕之歌','揭露敌人的防御破绽。'),
('bard_4','吟游诗人','4','ward','5','英雄赞歌','鼓舞一名队员抵挡伤害。'),
('bard_5','吟游诗人','5','damage','30','破晓乐章','用声浪击溃敌人。'),
('bard_6','吟游诗人','6','heal','39','不朽叙事','用传唱的故事挽回生命。'),
('paladin_1','圣武士','1','damage','13','炽誓','武器附着誓约火焰。'),
('paladin_2','圣武士','2','heal','17','守护祷文','治愈同伴的伤势。'),
('paladin_3','圣武士','3','ward','4','钢铁光环','保护身边的同伴。'),
('paladin_4','圣武士','4','damage','26','裁决之剑','将誓约化为一道剑光。'),
('paladin_5','圣武士','5','heal','33','复原圣歌','使濒死的同伴苏醒。'),
('paladin_6','圣武士','6','damage','41','破晓圣裁','倾尽神圣力量裁决敌人。')
on conflict(id) do update set profession=excluded.profession,ring=excluded.ring,kind=excluded.kind,amount=excluded.amount,name=excluded.name,description=excluded.description;

create or replace function public.campaign_level(p_chapter integer) returns integer language sql immutable set search_path=public,pg_temp as $$ select least(12,1+greatest(0,p_chapter)*2/5) $$;
create or replace function public.campaign_slots(p_level integer) returns jsonb language sql immutable set search_path=public,pg_temp as $$
 select jsonb_build_array(0,case when p_level>=1 then least(4,2+(p_level-1)/2) else 0 end,
 case when p_level>=3 then least(3,1+(p_level-3)/2) else 0 end,
 case when p_level>=5 then least(3,1+(p_level-5)/2) else 0 end,
 case when p_level>=7 then least(2,1+(p_level-7)/2) else 0 end,
 case when p_level>=9 then 1 else 0 end,case when p_level>=11 then 1 else 0 end) $$;
revoke all on function public.campaign_level(integer),public.campaign_slots(integer) from public,anon,authenticated;

create or replace function public.party_snapshot(p_code text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
 if auth.uid() is null or not exists(select 1 from public.players where room_code=upper(p_code) and user_id=auth.uid()) then raise exception 'NOT_MEMBER'; end if;
 select jsonb_build_object('room',r.code,'players',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'class_name',p.class_name,'is_host',p.is_host,'is_ready',p.is_ready,'hp',p.hp,'max_hp',p.max_hp,'ac',p.ac,'stats',p.stats,'inventory',p.inventory,'equipment',p.equipment,'gold',p.gold,'death_failures',p.death_failures,'death_successes',p.death_successes,'last_seen',p.last_seen,'level',p.level,'spell_slots',p.spell_slots,'ability_charges',p.ability_charges) order by p.created_at) from public.players p where p.room_code=r.code and p.user_id is not null),'[]'::jsonb),'me',(select p.id from public.players p where p.room_code=r.code and p.user_id=auth.uid()),'state',coalesce(g.state,'{}'::jsonb),'messages',coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from (select id,sender,body,kind,created_at from public.messages where room_code=r.code order by id desc limit 100) m),'[]'::jsonb)) into result from public.rooms r left join public.game_states g on g.room_code=r.code where r.code=upper(p_code);
 return result;
end $$;
create or replace function public.party_character(p_code text,p_uid uuid,p_name text,p_class text,p_host boolean) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_stats jsonb; v_hp int; v_ac int;
begin
 if p_uid<>auth.uid() then raise exception 'INVALID_IDENTITY'; end if;
 if exists(select 1 from public.players where room_code=p_code and name=p_name) then raise exception 'NAME_TAKEN'; end if;
 v_stats:=case p_class when '战士' then '[16,12,14,10,10,10]' when '游荡者' then '[10,16,12,12,10,12]' when '法师' then '[8,12,12,16,12,10]' when '牧师' then '[12,10,14,10,16,12]' when '游侠' then '[12,16,12,12,14,10]' when '圣武士' then '[16,10,14,10,12,16]' else '[10,14,12,12,10,16]' end::jsonb;
 v_hp:=case p_class when '战士' then 14 when '法师' then 8 when '牧师' then 11 when '游侠' then 11 when '圣武士' then 13 else 10 end;
 v_ac:=case p_class when '战士' then 16 when '牧师' then 15 when '圣武士' then 16 when '游侠' then 14 when '游荡者' then 14 when '吟游诗人' then 13 else 12 end;
 insert into public.players(room_code,user_id,name,class_name,is_host,hp,max_hp,ac,stats) values(p_code,p_uid,p_name,p_class,p_host,v_hp,v_hp,v_ac,v_stats);
end $$;
create or replace function public.party_command(p_code text, p_action text, p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_name text; v_class text; v_id bigint; v_host boolean; v_state jsonb; v_players int; v_unready int; v_target bigint; v_roll int; v_bonus int; v_dc int; v_dmg int; v_hp int; v_ac int; v_idx int; v_flags jsonb; v_clues jsonb; v_combat jsonb; v_turn bigint; v_next bigint; v_enemy_hp int; v_log text; v_chars text:='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; v_rand bytea; v_try int; v_newcode text; v_stats jsonb; v_max int; v_init jsonb; v_ord bigint; v_scene jsonb; v_key text; v_skill text; v_enemy jsonb; v_aid boolean;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 if p_action='create' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人','圣武士') then raise exception 'INVALID_CHARACTER'; end if;
  for v_try in 1..10 loop
   v_rand:=decode(replace(gen_random_uuid()::text,'-',''),'hex'); v_newcode:='';
   for v_idx in 0..4 loop v_newcode:=v_newcode||substr(v_chars,1+get_byte(v_rand,v_idx)%length(v_chars),1); end loop;
   insert into public.rooms(code) values(v_newcode) on conflict do nothing;
   exit when found;
  end loop;
  if v_try=10 and not found then raise exception 'CODE_EXHAUSTED'; end if;
  v_code:=v_newcode;
  perform public.party_character(v_code,v_uid,v_name,v_class,true);
  insert into public.game_states(room_code,state) values(v_code,jsonb_build_object('started',false,'chapter',0,'flags','[]'::jsonb,'clues','[]'::jsonb,'quest','追查消失的议员','completed_quests','[]'::jsonb,'combat',null,'version',1,'ending',null));
  return public.party_snapshot(v_code);
 end if;
 if p_action='join' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人','圣武士') then raise exception 'INVALID_CHARACTER'; end if;
  perform 1 from public.rooms where code=v_code for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if exists(select 1 from public.game_states where room_code=v_code and (state->>'started')::boolean) then raise exception 'GAME_STARTED'; end if;
  if exists(select 1 from public.players where room_code=v_code and user_id=v_uid) then return public.party_snapshot(v_code); end if;
  select count(*) into v_players from public.players where room_code=v_code and user_id is not null;
  if v_players>=5 then raise exception 'ROOM_FULL'; end if;
  perform public.party_character(v_code,v_uid,v_name,v_class,false);
  return public.party_snapshot(v_code);
 end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select id,name,is_host,hp,ac into v_id,v_name,v_host,v_hp,v_ac from public.players where room_code=v_code and user_id=v_uid;
 if v_id is null then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if p_action='heartbeat' then update public.players set last_seen=now() where id=v_id; return public.party_snapshot(v_code); end if;
 if p_action='leave' then
  delete from public.players where id=v_id;
  if v_host then update public.players set is_host=true,is_ready=false where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1); end if;
  return jsonb_build_object('left',true);
 end if;
 if p_action='claim_host' then
  if not exists(select 1 from public.players where room_code=v_code and is_host and user_id is not null and last_seen>now()-interval '5 minutes') then
   update public.players set is_host=false where room_code=v_code;
   update public.players set is_host=true where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1);
  end if;
  return public.party_snapshot(v_code);
 end if;
 if p_action='ready' then
  if (v_state->>'started')::boolean then raise exception 'ALREADY_STARTED'; end if;
  update public.players set is_ready=not is_ready where id=v_id;
 elsif p_action='start' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  select count(*),count(*) filter(where not is_ready) into v_players,v_unready from public.players where room_code=v_code and user_id is not null;
  if v_players<2 or v_players>5 or v_unready>0 then raise exception 'PARTY_NOT_READY'; end if;
  v_state:=jsonb_set(v_state,'{started}','true'::jsonb);
  v_log:='冒险开始。';
 elsif p_action='chat' then
  v_log:=left(trim(coalesce(p_payload->>'body','')),500);
  if length(v_log)<1 then raise exception 'EMPTY_MESSAGE'; end if;
 elsif p_action='roll' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  -- The browser chooses a skill and DC; the modifier comes from the authenticated character.
  if p_payload->>'skill' not in ('调查','洞悉','说服','潜行','运动','奥秘','求生') then raise exception 'INVALID_SKILL'; end if;
  select floor(((stats->>case p_payload->>'skill' when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 else 5 end)::int-10)/2.0)::int
    + case when (class_name='战士' and p_payload->>'skill'='运动') or (class_name='游荡者' and p_payload->>'skill' in ('调查','潜行')) or (class_name='法师' and p_payload->>'skill'='奥秘') or (class_name='牧师' and p_payload->>'skill'='洞悉') or (class_name='游侠' and p_payload->>'skill'='求生') or (class_name='吟游诗人' and p_payload->>'skill'='说服') or (class_name='圣武士' and p_payload->>'skill' in ('运动','说服')) then 2 else 0 end into v_bonus from public.players where id=v_id;
  v_dc:=greatest(5,least(30,coalesce((p_payload->>'dc')::int,15)));
  v_roll:=floor(random()*20)::int+1;
  v_log:=left(coalesce(p_payload->>'skill','技能'),30)||'检定 D20='||v_roll||'，加值 '||v_bonus||'，DC '||v_dc||'：'||case when v_roll=20 then '大成功' when v_roll=1 then '大失败' when v_roll+v_bonus>=v_dc then '成功' else '失败' end;
 elsif p_action='explore' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_idx:=coalesce((p_payload->>'index')::int,-1);
  if v_idx<0 or v_idx>1 then raise exception 'INVALID_ENCOUNTER'; end if;
  v_key:=(v_state->>'chapter')||':'||v_idx;
  if coalesce(v_state->'explored','[]'::jsonb) ? v_key then raise exception 'ALREADY_EXPLORED'; end if;
  select scenes->v_idx into v_scene from public.campaign_chapters where id=(v_state->>'chapter')::int;
  if v_scene is null then raise exception 'ENCOUNTER_UNAVAILABLE'; end if;
  v_skill:=v_scene->>'skill'; v_dc:=(v_scene->>'dc')::int;
  select floor(((stats->>case v_skill when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 else 5 end)::int-10)/2.0)::int
   + case when (class_name='战士' and v_skill='运动') or (class_name='游荡者' and v_skill in ('调查','潜行')) or (class_name='法师' and v_skill='奥秘') or (class_name='牧师' and v_skill='洞悉') or (class_name='游侠' and v_skill='求生') or (class_name='吟游诗人' and v_skill='说服') or (class_name='圣武士' and v_skill in ('运动','说服')) then 2 else 0 end into v_bonus from public.players where id=v_id;
  v_roll:=floor(random()*20)::int+1;
  v_state:=jsonb_set(v_state,'{explored}',coalesce(v_state->'explored','[]'::jsonb)||to_jsonb(v_key));
  if v_roll=20 or (v_roll<>1 and v_roll+v_bonus>=v_dc) then
   v_clues:=coalesce(v_state->'clues','[]'::jsonb); v_flags:=coalesce(v_state->'flags','[]'::jsonb);
   if not v_clues ? (v_scene->>'clue') then v_clues:=v_clues||to_jsonb(v_scene->>'clue'); end if;
   if not v_flags ? (v_scene->>'flag') then v_flags:=v_flags||to_jsonb(v_scene->>'flag'); end if;
   v_state:=jsonb_set(jsonb_set(v_state,'{clues}',v_clues),'{flags}',v_flags);
   v_log:=v_scene->>'success';
  else v_log:=v_scene->>'failure'; end if;
  v_log:=(v_scene->>'label')||' · '||v_skill||' D20='||v_roll||'+'||v_bonus||' / DC '||v_dc||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'：'||v_log;
 elsif p_action='choice' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)=(v_state->>'chapter')::int then raise exception 'CHOICE_ALREADY_MADE'; end if;
  if not (coalesce(v_state->'explored','[]'::jsonb) ? ((v_state->>'chapter')||':0')) or not (coalesce(v_state->'explored','[]'::jsonb) ? ((v_state->>'chapter')||':1')) then raise exception 'EXPLORE_BEFORE_CHOICE'; end if;
  v_idx:=coalesce((p_payload->>'index')::int,-1);
  if v_idx<0 or v_idx>1 then raise exception 'INVALID_CHOICE'; end if;
  select choices->v_idx into p_payload from public.campaign_chapters where id=(v_state->>'chapter')::int;
  if p_payload is null then raise exception 'INVALID_CHOICE'; end if;
  v_flags:=coalesce(v_state->'flags','[]'::jsonb); v_clues:=coalesce(v_state->'clues','[]'::jsonb);
  if length(coalesce(p_payload->>'flag',''))>0 and not v_flags ? (p_payload->>'flag') then v_flags:=v_flags||to_jsonb(left(p_payload->>'flag',40)); end if;
  if length(coalesce(p_payload->>'clue',''))>0 and not v_clues ? (p_payload->>'clue') then v_clues:=v_clues||to_jsonb(left(p_payload->>'clue',60)); end if;
  v_state:=jsonb_set(jsonb_set(v_state,'{flags}',v_flags),'{clues}',v_clues);
  v_state:=jsonb_set(v_state,'{chosen_chapter}',to_jsonb((v_state->>'chapter')::int));
  v_log:='选择：'||left(coalesce(p_payload->>'label',''),80);
 elsif p_action='advance' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if (v_state->>'chapter')::int>=29 then raise exception 'CAMPAIGN_COMPLETE'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)<>coalesce((v_state->>'chapter')::int,0) then raise exception 'CHOOSE_BEFORE_ADVANCE'; end if;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and coalesce((v_state#>>'{combat,hp}')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
  v_idx:=least(29,coalesce((v_state->>'chapter')::int,0)+1);
  v_state:=jsonb_set(jsonb_set(v_state,'{chapter}',to_jsonb(v_idx)),'{completed_quests}',coalesce(v_state->'completed_quests','[]'::jsonb)||to_jsonb(v_idx-1));
  -- Story milestones grant levels and spell circles to every member atomically.
  update public.players set max_hp=max_hp+(public.campaign_level(v_idx)-level)*case class_name when '战士' then 6 when '圣武士' then 6 when '法师' then 4 else 5 end,
    hp=hp+(public.campaign_level(v_idx)-level)*case class_name when '战士' then 6 when '圣武士' then 6 when '法师' then 4 else 5 end,
    level=public.campaign_level(v_idx),spell_slots=public.campaign_slots(public.campaign_level(v_idx)),ability_charges=2
    where room_code=v_code and user_id is not null and level<public.campaign_level(v_idx);
  -- A completed fight grants a camp rest before the next scene. Downed allies need healing first.
  if coalesce((v_state#>>'{combat,hp}')::int,-1)=0 then
   update public.players set hp=max_hp,spell_slots=public.campaign_slots(level),ability_charges=2 where room_code=v_code and user_id is not null and hp>0;
  end if;
  select details into v_enemy from public.campaign_battles where chapter_id=v_idx;
  if v_enemy is not null then
   select count(*) into v_players from public.players where room_code=v_code and user_id is not null;
   v_aid:=coalesce(v_state->'flags','[]'::jsonb) ? (v_enemy->>'aid');
   v_enemy_hp:=(v_enemy->>'hp')::int+greatest(0,v_players-2)*7-case when v_aid then 5 else 0 end;
   select jsonb_agg(jsonb_build_object('id',id,'roll',roll) order by roll desc,id),(array_agg(id order by roll desc,id))[1] into v_init,v_turn from (select id,floor(random()*20)::int+1 as roll from public.players where room_code=v_code and user_id is not null and hp>0) i;
   v_state:=jsonb_set(v_state,'{combat}',jsonb_build_object('name',v_enemy->>'name','hp',v_enemy_hp,'max_hp',v_enemy_hp,'ac',(v_enemy->>'ac')::int-case when v_aid then 1 else 0 end,'attack_bonus',(v_enemy->>'attack')::int,'damage_min',(v_enemy->>'min')::int,'damage_die',(v_enemy->>'die')::int,'turn',v_turn,'initiative',v_init,'round',1));
  else v_state:=jsonb_set(v_state,'{combat}','null'::jsonb); end if;
  if v_idx=29 then v_state:=jsonb_set(v_state,'{ending}',to_jsonb(case when (v_state->'flags') ? 'council' then '公民议会重建' when (v_state->'flags') ? 'autonomy' then '地下自治联盟' when jsonb_array_length(v_state->'flags')>=18 then '城市共同体' else '艰难的黎明' end)); end if;
  if v_idx%5=0 then update public.players set gold=gold+10 where room_code=v_code and user_id is not null; end if;
  v_log:='推进至第 '||(v_idx+1)||' 章。'||case when v_idx%5=0 then ' 队员各获 10 金币。' else '' end||case when v_enemy is not null then ' 遭遇：'||(v_enemy->>'name')||'。'||case when v_aid then v_enemy->>'aidText' else '' end else '' end;
 elsif p_action='attack' then
  v_combat:=v_state->'combat';
  if v_combat is null or v_combat='null'::jsonb or (v_combat->>'hp')::int<=0 then raise exception 'NO_COMBAT'; end if;
  if (v_combat->>'turn')::bigint<>v_id then raise exception 'NOT_YOUR_TURN'; end if;
  if v_hp<=0 then raise exception 'DOWNED'; end if;
  select case class_name when '战士' then 5 when '游荡者' then 5 when '法师' then 5 when '游侠' then 5 when '圣武士' then 5 else 4 end into v_bonus from public.players where id=v_id;
  v_roll:=floor(random()*20)::int+1; v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_combat->>'ac')::int) then 0 else (floor(random()*8)::int+1)+v_bonus+case when v_roll=20 then (floor(random()*8)::int+1) else 0 end end;
  v_enemy_hp:=greatest(0,(v_combat->>'hp')::int-v_dmg); v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(v_enemy_hp));
  v_log:='攻击 D20='||v_roll||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'，伤害 '||v_dmg;
  if v_enemy_hp>0 then
   select ord into v_ord from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) where (item->>'id')::bigint=v_id;
   select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where e.ord>v_ord and p.hp>0 order by e.ord limit 1;
   if v_next is null then
    -- The enemy acts once after the party round.
    v_roll:=floor(random()*20)::int+1;
    if v_roll=20 or (v_roll<>1 and v_roll+coalesce((v_combat->>'attack_bonus')::int,4)>=v_ac+coalesce((v_combat->'wards'->>v_id::text)::int,0)) then
     v_dmg:=floor(random()*coalesce((v_combat->>'damage_die')::int,6))::int+coalesce((v_combat->>'damage_min')::int,3);
     update public.players set hp=greatest(0,hp-v_dmg) where id=v_id;
     v_log:=v_log||'；敌人反击 '||v_name||'，伤害 '||v_dmg;
    else v_log:=v_log||'；敌人反击未命中'; end if;
    v_combat:=jsonb_set(v_combat,'{wards}',coalesce(v_combat->'wards','{}'::jsonb)-v_id::text);
    select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where p.hp>0 order by e.ord limit 1;
    v_combat:=jsonb_set(v_combat,'{round}',to_jsonb((v_combat->>'round')::int+1));
   end if;
   if v_next is null then v_log:=v_log||'；队伍全员倒地'; end if;
   v_combat:=jsonb_set(v_combat,'{turn}',coalesce(to_jsonb(v_next),'null'::jsonb));
  else update public.players set gold=gold+5 where room_code=v_code and user_id is not null; v_log:=v_log||'；敌人倒下，队员各获得 5 金币'; end if;
  v_state:=jsonb_set(v_state,'{combat}',v_combat);
 elsif p_action='heal' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_target:=coalesce((p_payload->>'target')::bigint,v_id);
  if not exists(select 1 from public.players where id=v_target and room_code=v_code and user_id is not null) then raise exception 'INVALID_TARGET'; end if;
  if not (select inventory ? '治疗药水' from public.players where id=v_id) then raise exception 'NO_POTION'; end if;
  update public.players set inventory=inventory-'治疗药水' where id=v_id;
  update public.players set hp=least(max_hp,hp+8),death_failures=0,death_successes=0 where id=v_target and hp>=0;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_target)); end if;
  v_log:='使用治疗药水，恢复 8 HP。';
 elsif p_action='buy' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if p_payload->>'item'='治疗药水' then
   update public.players set gold=gold-10,inventory=inventory||'"治疗药水"'::jsonb where id=v_id and gold>=10;
   if not found then raise exception 'NOT_ENOUGH_GOLD'; end if;
   v_log:='购买治疗药水，花费 10 金币。';
  elsif p_payload->>'item'='盾牌' then
   if (select inventory ? '盾牌' or equipment ? '盾牌' from public.players where id=v_id) then raise exception 'ALREADY_OWNED'; end if;
   update public.players set gold=gold-30,inventory=inventory||'"盾牌"'::jsonb where id=v_id and gold>=30;
   if not found then raise exception 'NOT_ENOUGH_GOLD'; end if;
   v_log:='购买盾牌，花费 30 金币。';
  else raise exception 'UNKNOWN_ITEM'; end if;
 elsif p_action='equip' then
  if p_payload->>'item'<>'盾牌' or not (select inventory ? '盾牌' from public.players where id=v_id) then raise exception 'ITEM_NOT_IN_BAG'; end if;
  update public.players set inventory=inventory-'盾牌',equipment=equipment||'"盾牌"'::jsonb,ac=ac+1 where id=v_id;
  v_log:='装备盾牌，AC +1。';
 elsif p_action='death_save' then
  if v_hp<>0 then raise exception 'NOT_DOWNED'; end if;
  v_roll:=floor(random()*20)::int+1;
  if v_roll=20 then update public.players set hp=1,death_failures=0,death_successes=0 where id=v_id;
   if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_id)); end if;
  elsif v_roll=1 then update public.players set death_failures=least(3,death_failures+2) where id=v_id;
  elsif v_roll>=10 then update public.players set death_successes=least(3,death_successes+1) where id=v_id;
  else update public.players set death_failures=least(3,death_failures+1) where id=v_id; end if;
  v_log:='死亡豁免 D20='||v_roll||case when v_roll=20 then '，恢复 1 HP' else '' end;
 else raise exception 'UNKNOWN_ACTION'; end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 if v_log is not null then insert into public.messages(room_code,sender,body,kind) values(v_code,v_name,v_log,p_action); end if;
 return public.party_snapshot(v_code);
end $$;

-- An authenticated room member may use only a power belonging to their class.
-- Room and state locks serialize concurrent combat turns and resource consumption.
create or replace function public.party_power(p_code text,p_id text,p_target bigint default null,p_slot integer default 0)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_actor public.players%rowtype; v_target public.players%rowtype;
 v_state jsonb; v_combat jsonb; v_power public.campaign_powers%rowtype; v_slots jsonb; v_slot integer:=coalesce(p_slot,0); v_roll integer; v_bonus integer; v_amount integer;
 v_hp integer; v_next bigint; v_ord bigint; v_dmg integer; v_log text; v_stat integer; v_warr integer;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select * into v_actor from public.players where room_code=v_code and user_id=v_uid;
 if not found then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if not coalesce((v_state->>'started')::boolean,false) then raise exception 'NOT_STARTED'; end if;
 v_combat:=v_state->'combat';
 if p_id='rest' then
   if not v_actor.is_host then raise exception 'HOST_ONLY'; end if;
   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>0 then raise exception 'COMBAT_ACTIVE'; end if;
   if coalesce((v_state->>'rested_chapter')::int,-1)=(v_state->>'chapter')::int then raise exception 'ALREADY_RESTED'; end if;
   update public.players set hp=max_hp,death_failures=0,death_successes=0,spell_slots=public.campaign_slots(level),ability_charges=2
    where room_code=v_code and user_id is not null and death_failures<3;
   v_state:=jsonb_set(v_state,'{rested_chapter}',to_jsonb((v_state->>'chapter')::int));
   v_log:='队伍长休：恢复生命、职业技能和法术位（本章限一次）。';
 else
   select * into v_power from public.campaign_powers where id=p_id and profession=v_actor.class_name;
   if not found then raise exception 'POWER_NOT_KNOWN'; end if;
   if v_actor.hp<=0 or v_actor.death_failures>=3 then raise exception 'DOWNED'; end if;
   if v_power.ring=0 then
     if v_slot<>0 or v_actor.ability_charges<=0 then raise exception 'NO_ABILITY_CHARGES'; end if;
     update public.players set ability_charges=ability_charges-1 where id=v_actor.id;
   else
     if v_slot<v_power.ring or v_slot>6 or v_actor.level<2*v_power.ring-1 then raise exception 'SPELL_CIRCLE_LOCKED'; end if;
     v_slots:=v_actor.spell_slots;
     if coalesce((v_slots->>v_slot)::int,0)<=0 then raise exception 'NO_SPELL_SLOT'; end if;
     update public.players set spell_slots=jsonb_set(spell_slots,array[v_slot::text],to_jsonb((v_slots->>v_slot)::int-1)) where id=v_actor.id;
   end if;
   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>0 then
     if (v_combat->>'turn')::bigint<>v_actor.id then raise exception 'NOT_YOUR_TURN'; end if;
   elsif v_power.kind<>'heal' then raise exception 'NO_COMBAT'; end if;
   v_amount:=v_power.amount+greatest(0,v_slot-v_power.ring)*2;
   if v_power.kind in ('heal','ward') then
     select * into v_target from public.players where id=coalesce(p_target,v_actor.id) and room_code=v_code and user_id is not null;
     if not found then raise exception 'INVALID_TARGET'; end if;
     if v_target.death_failures>=3 then raise exception 'TARGET_DEAD'; end if;
   end if;
   if v_power.kind='heal' then
     v_amount:=v_amount+floor(random()*6)::int+1;
     update public.players set hp=least(max_hp,hp+v_amount),death_failures=0,death_successes=0 where id=v_target.id;
     v_log:=v_power.name||'：'||v_target.name||' 恢复 '||least(v_amount,v_target.max_hp-v_target.hp)||' HP';
   elsif v_power.kind='ward' then
     v_combat:=jsonb_set(v_combat,'{wards}',jsonb_set(coalesce(v_combat->'wards','{}'::jsonb),array[v_target.id::text],to_jsonb(greatest(v_amount,coalesce((v_combat->'wards'->>v_target.id::text)::int,0))),true));
     v_log:=v_power.name||'：'||v_target.name||' 下一次受攻击时 AC +'||v_amount;
   elsif v_power.kind='weaken' then
     v_combat:=jsonb_set(jsonb_set(v_combat,'{ac}',to_jsonb(greatest(8,(v_combat->>'ac')::int-v_amount))),'{attack_bonus}',to_jsonb(greatest(0,(v_combat->>'attack_bonus')::int-1)));
     v_log:=v_power.name||'：敌人 AC -'||v_amount||'、攻击 -1';
   elsif v_power.kind='damage' then
     v_stat:=case v_actor.class_name when '法师' then 3 when '牧师' then 4 when '游侠' then 4 when '吟游诗人' then 5 when '游荡者' then 1 when '圣武士' then 5 else 0 end;
     v_bonus:=floor(((v_actor.stats->>v_stat)::int-10)/2.0)::int+2+(v_actor.level-1)/4;
     v_roll:=floor(random()*20)::int+1;
     v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_combat->>'ac')::int) then 0 else v_amount+floor(random()*6)::int+1+case when v_roll=20 then v_amount else 0 end end;
     v_hp:=greatest(0,(v_combat->>'hp')::int-v_dmg);
     v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(v_hp));
     v_log:=v_power.name||' D20='||v_roll||'+'||v_bonus||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'，伤害 '||v_dmg;
   else raise exception 'UNKNOWN_EFFECT'; end if;

   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>=0 then
     if (v_combat->>'hp')::int=0 then
       if v_power.kind='damage' then update public.players set gold=gold+5 where room_code=v_code and user_id is not null; v_log:=v_log||'；敌人倒下，全队各获 5 金币'; end if;
     else
       select ord into v_ord from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) where (item->>'id')::bigint=v_actor.id;
       select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where e.ord>v_ord and p.hp>0 order by e.ord limit 1;
       if v_next is null then
         v_roll:=floor(random()*20)::int+1;
         select hp,ac into v_hp,v_bonus from public.players where id=v_actor.id;
         v_warr:=coalesce((v_combat->'wards'->>v_actor.id::text)::int,0);
         if v_roll=20 or (v_roll<>1 and v_roll+(v_combat->>'attack_bonus')::int>=v_bonus+v_warr) then
           v_dmg:=floor(random()*(v_combat->>'damage_die')::int)::int+(v_combat->>'damage_min')::int;
           update public.players set hp=greatest(0,hp-v_dmg) where id=v_actor.id;
           v_log:=v_log||'；敌人反击 '||v_actor.name||'，伤害 '||v_dmg;
         else v_log:=v_log||'；敌人反击未命中'; end if;
         v_combat:=jsonb_set(v_combat,'{wards}',coalesce(v_combat->'wards','{}'::jsonb)-v_actor.id::text);
         select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality as e(item,ord) join public.players p on p.id=(item->>'id')::bigint where p.hp>0 order by e.ord limit 1;
         v_combat:=jsonb_set(v_combat,'{round}',to_jsonb((v_combat->>'round')::int+1));
       end if;
       v_combat:=jsonb_set(v_combat,'{turn}',coalesce(to_jsonb(v_next),'null'::jsonb));
     end if;
     v_state:=jsonb_set(v_state,'{combat}',v_combat);
   end if;
 end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 insert into public.messages(room_code,sender,body,kind) values(v_code,v_actor.name,v_log,'power');
 return public.party_snapshot(v_code);
end $$;
revoke all on function public.party_snapshot(text),public.party_character(text,uuid,text,text,boolean),public.party_command(text,text,jsonb),public.party_power(text,text,bigint,integer) from public,anon,authenticated;
grant execute on function public.party_snapshot(text),public.party_command(text,text,jsonb),public.party_power(text,text,bigint,integer) to authenticated;

-- Existing campaign parties catch up to the chapter milestone once on migration.
update public.players p set level=public.campaign_level((g.state->>'chapter')::int),
 max_hp=p.max_hp+(public.campaign_level((g.state->>'chapter')::int)-p.level)*case p.class_name when '战士' then 6 when '法师' then 4 else 5 end,
 hp=p.hp+(public.campaign_level((g.state->>'chapter')::int)-p.level)*case p.class_name when '战士' then 6 when '法师' then 4 else 5 end,
 spell_slots=public.campaign_slots(public.campaign_level((g.state->>'chapter')::int)),ability_charges=2
from public.game_states g where g.room_code=p.room_code and p.user_id is not null and p.level<public.campaign_level((g.state->>'chapter')::int);
