-- Generated by npm run areas:sql. Original regional content and server-owned actions.
alter table public.players add column if not exists is_companion boolean not null default false;
alter table public.players add column if not exists experience integer not null default 0;
alter table public.campaign_items add column if not exists rarity text not null default '普通';
alter table public.campaign_items add column if not exists description text not null default '';
alter table public.campaign_items add column if not exists effect text not null default '';
create table if not exists public.uc_areas(id text primary key,name text not null,unlock_chapter integer not null,description text not null,places jsonb not null);
create table if not exists public.uc_npcs(id text primary key,area text not null references public.uc_areas(id),name text not null,role text not null,background text not null,personality text not null,attitude text not null,intro text not null,topics jsonb not null);
create table if not exists public.uc_quests(id text primary key,name text not null,giver text not null references public.uc_npcs(id),area text not null references public.uc_areas(id),description text not null,reward jsonb not null,stages jsonb not null);
create table if not exists public.uc_battles(id text primary key,name text not null,intro text not null,foes jsonb not null);
alter table public.uc_areas enable row level security;
revoke all on public.uc_areas from public,anon,authenticated;
alter table public.uc_npcs enable row level security;
revoke all on public.uc_npcs from public,anon,authenticated;
alter table public.uc_quests enable row level security;
revoke all on public.uc_quests from public,anon,authenticated;
alter table public.uc_battles enable row level security;
revoke all on public.uc_battles from public,anon,authenticated;
insert into public.uc_areas values('kegs','三只旧酒桶',0,'铜灯悬在三只空酒桶上方。雨夜的信使、失业抄写员与城防家属在这里交换不肯写进公文的事实。','[["壁炉旁的账桌","一叠欠条压着酒馆旧地图。"],["后巷的雨水槽","水里浮着蓝色封蜡和碎纸。"],["楼上的空房","窗台可俯瞰通往奇迹高堂的搬货路。"]]'::jsonb) on conflict(id) do update set name=excluded.name,unlock_chapter=excluded.unlock_chapter,description=excluded.description,places=excluded.places;
insert into public.uc_areas values('wonders','奇迹高堂',0,'拱顶下，工匠把护甲、抄写卷轴与古怪仪器摆成可触摸的展台。库存随城中风波和商路逐渐更新。','[["试刃台","铁屑里混有刻着私人纹章的黄铜。"],["封存柜","卷轴的登记日期与真实装订时间不符。"],["修复室","每件入库物品都有两套称重记录。"]]'::jsonb) on conflict(id) do update set name=excluded.name,unlock_chapter=excluded.unlock_chapter,description=excluded.description,places=excluded.places;
insert into public.uc_areas values('hall','至高大厅',10,'大厅的听证席并不比走廊更安静。官员、递信人和议会顾问在庭审前抢先改写事实。','[["公开记录廊","被涂掉的旁听者姓名仍在纸背留下凹痕。"],["旧印室","封条从内侧开启，又被人细心粘回。"],["议事高台","此处能听见幕后的第二套表决钟声。"]]'::jsonb) on conflict(id) do update set name=excluded.name,unlock_chapter=excluded.unlock_chapter,description=excluded.description,places=excluded.places;
insert into public.uc_areas values('walls','上城区城墙',15,'巡逻灯在雾中依次暗下。城外坡道和排水暗门给守军留下无法解释的足迹。','[["北段瞭望台","铜镜偏离了既定的传讯角度。"],["排水暗门","泥土上有五种靴印，四种朝外。"],["军需仓","一批没有编号的箭矢藏在盐袋底下。"]]'::jsonb) on conflict(id) do update set name=excluded.name,unlock_chapter=excluded.unlock_chapter,description=excluded.description,places=excluded.places;
insert into public.uc_npcs values('mara','kegs','玛拉·雾杯','酒馆老板','曾替巡夜队保管密函，拒绝再让客人在店里无声失踪。','直率，记账严谨','谨慎欢迎','店里每一张桌子都能谈事，但请别让别人替你付账。','[{"prompt":"昨夜有人把一只空杯倒扣在壁炉边，里面却有盐。","options":[{"label":"谁留下的？","reply":"穿蓝斗篷的搬运工；他一直盯着后巷。","follow":"玛拉递给你一张写着搬运时辰的纸。","attitude":1,"flag":"mara_shift"},{"label":"为什么有盐？","reply":"用来显露杯沿的指纹。他想证明自己没有碰过密函。","follow":"你看见杯底有半枚工坊印记。","attitude":0,"flag":"salt_cup"},{"label":"可以给我们一份工作吗？","reply":"我有几件麻烦，先查清谁有胆量接。","follow":"她指向墙上的委托板。","attitude":1,"flag":"mara_work"}]},{"prompt":"今早巡逻的人只喝热水。他们说城墙下面在敲第二遍钟。","options":[{"label":"你相信他们吗？","reply":"相信他们害怕是真的，不代表他们看见的全是真的。","follow":"她建议从排水暗门查起。","attitude":1,"flag":"second_bell"},{"label":"能请他们作证吗？","reply":"除非先保证不会把名单送去大厅。","follow":"玛拉肯借楼上房间作证人藏身处。","attitude":1,"flag":"safe_room"},{"label":"那先来顿饭。","reply":"炖菜要六枚金币，热酒要四枚。醒着的人更适合调查。","follow":"她把菜单推到你的手边。","attitude":0,"flag":"menu"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('tobin','kegs','托宾·纸雀','失业抄写员','拒绝改写物资出入簿后失去大厅差事。','焦虑而敏锐','戒备','我可以辨认字迹，但别在酒馆大声叫我的旧职务。','[{"prompt":"有人把一笔采购记成三笔，字迹故意学得像我。","options":[{"label":"给我看看原账。","reply":"原账撕走了页角，留下的压痕指向高堂封存柜。","follow":"托宾画出压痕里的序号。","attitude":1,"flag":"pressed_ledger"},{"label":"谁会冒你的名？","reply":"大厅旧印室有四人拿得到我的印章。","follow":"名单中一个名字被他划得极重。","attitude":0,"flag":"four_signers"},{"label":"你可能也参与了。","reply":"若我有份，就不会躲在发霉的楼板下面。","follow":"他冷了脸，却没有赶你走。","attitude":-1,"flag":"tobin_doubt"}]},{"prompt":"我的妹妹在墙上服役。她最近的信每封都少一行。","options":[{"label":"你想让我们去找她？","reply":"找到她，也请先听她自己的说法。","follow":"他交给你一张折了三次的地图。","attitude":1,"flag":"tobin_sister"},{"label":"缺的是什么？","reply":"每封都剪去夜间换岗的时间。","follow":"你发现裁纸刀口与大厅文书一致。","attitude":0,"flag":"cut_letters"},{"label":"先把信公开。","reply":"请不要让她为我的冲动受罚。","follow":"他收回其中一封，留给你另一封。","attitude":-1,"flag":"public_letter"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('sera','kegs','瑟拉·火莓','厨师兼前军医','在一次边境撤离后辞去军职，坚持照顾受伤的普通人。','温和但不轻信军令','友善','先把湿衣服烘干。打仗前吃饱，吵架前喝水。','[{"prompt":"有个士兵把绷带藏在袖口，不敢去军医处。","options":[{"label":"伤从哪里来？","reply":"不是刀伤，是暗门铁栅刮出来的。","follow":"瑟拉记下铁锈颜色，供你比对。","attitude":1,"flag":"rust_bandage"},{"label":"你能救他吗？","reply":"能，但他得自己愿意进门。","follow":"她留了一份干净绷带。","attitude":1,"flag":"sera_care"},{"label":"他是不是逃兵？","reply":"伤口不会回答这个问题。","follow":"她的语气明显冷下来。","attitude":-1,"flag":"sera_distrust"}]},{"prompt":"我做的炖菜能补体力，但真正的伤要时间。","options":[{"label":"这份菜怎么做？","reply":"白豆慢炖，药草最后才放，不能久煮。","follow":"她给队伍端来一碗热汤。","attitude":1,"flag":"stew"},{"label":"有没有治伤药？","reply":"高堂有更强的药剂；我这里是普通食物。","follow":"她告诉你药剂的供货人。","attitude":0,"flag":"potions"},{"label":"你认识城墙军官吗？","reply":"有些人愿意救人，有些人只会签名。","follow":"她提起一份被压下的伤亡表。","attitude":0,"flag":"casualty_list"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('elric','wonders','艾尔里克·铜尺','高堂器械总管','从学徒升为总管，暗中保留每次失窃的修复记录。','精确而固执','正式接待','任何商品都能问价。想碰封存柜，先说清你找什么。','[{"prompt":"一架星盘少了可拆卸的第五环，却被登记为完整。","options":[{"label":"第五环有什么用？","reply":"它能把城墙灯号的间隔刻进金属。","follow":"他展示磨损方向不同的螺孔。","attitude":1,"flag":"fifth_ring"},{"label":"谁签的入库单？","reply":"我的印章是对的，签名的墨水却晚了三日。","follow":"他让你核对试刃台的黄铜。","attitude":0,"flag":"late_ink"},{"label":"你收了封口费吗？","reply":"若我收了，还会留这张错误的单据？","follow":"他把账簿合上了。","attitude":-1,"flag":"elric_suspect"}]},{"prompt":"柜台上的寻常装备供冒险者使用，卷轴须遵守抄写许可。","options":[{"label":"现在卖什么？","reply":"先看你们调查走到了哪里；危险的器物会逐步开放。","follow":"他指向标明稀有度的价签。","attitude":0,"flag":"stock"},{"label":"能定做护甲吗？","reply":"有图样和材料才行，先拿基本装备试身。","follow":"他量了量肩宽。","attitude":1,"flag":"fit_armor"},{"label":"为何锁住最贵的柜？","reply":"那不是地位问题，封印还在校准。","follow":"他记下你对稀有物品的兴趣。","attitude":-1,"flag":"sealed_stock"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('ilya','wonders','伊莉娅·棱光','半精灵奥术护卫','曾在城墙值夜，因拒绝伪造换岗报告被调来高堂。','冷静、有同情心','审慎观察','这把弓不是展品。我留在这里，是因为有人还在调查旧报告。','[{"prompt":"城墙排水暗门比军方承认的多一扇。","options":[{"label":"谁知道入口？","reply":"排水匠、一个文书，还有半队死去的士兵。","follow":"她画下一段可避开巡逻灯的路线。","attitude":1,"flag":"ilya_route"},{"label":"你愿意带路吗？","reply":"先证明你不会把目击者当诱饵。","follow":"她在桌上留下自己的巡逻徽章。","attitude":1,"flag":"ilya_trust"},{"label":"你在掩护谁？","reply":"我掩护还活着的人。","follow":"她握紧了弓弦。","attitude":-1,"flag":"ilya_anger"}]},{"prompt":"高堂的魔法卷轴本来要送去军需仓，后被改道。","options":[{"label":"能鉴定吗？","reply":"这张护盾卷轴仍完整，那张火焰卷轴被拆过封。","follow":"她指出卷轴蜡印的差异。","attitude":1,"flag":"scroll_trace"},{"label":"谁改了路线？","reply":"去看公开记录廊里的物资签收。","follow":"她递给你一份副本。","attitude":0,"flag":"supply_copy"},{"label":"你会加入我们吗？","reply":"找到真正的命令，再让我自己决定。","follow":"她把徽章重新放回衣领。","attitude":0,"flag":"ilya_wait"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('nemi','wonders','奈米·金丝','药剂师与卷轴修复师','为贫民诊所制作廉价药剂，和行会定价者争执多年。','诙谐，讨厌浪费','热情','药水标签要读三遍。卷轴读错一遍，屋顶就没了。','[{"prompt":"有人把治疗药水换成了不会愈合的染色水。","options":[{"label":"怎么辨别？","reply":"真药水摇晃时会在瓶口留银线，假货只有颜色。","follow":"她让你带走一张鉴定纸。","attitude":1,"flag":"silver_line"},{"label":"流向哪里？","reply":"一半在军需仓，一半在酒馆后巷转手。","follow":"她记得搬运人的左手套有破洞。","attitude":0,"flag":"broken_glove"},{"label":"是不是你卖的？","reply":"要害人，我会选不那么容易闻出来的东西。","follow":"她看了你一眼，继续工作。","attitude":-1,"flag":"nemi_suspect"}]},{"prompt":"修复室的秤从不说谎，记账的人却会。","options":[{"label":"帮我核对重量。","reply":"星盘少了第五环，账面重量仍未变化。","follow":"她交给你旧秤码。","attitude":1,"flag":"old_weights"},{"label":"稀有器物何时上架？","reply":"等封印稳固，也等你们能负担得起。","follow":"她展示后期才开放的陈列柜。","attitude":0,"flag":"rare_vault"},{"label":"我想要补给。","reply":"炖菜在酒馆，药水和卷轴在这里。","follow":"她报了一个实在的价格。","attitude":0,"flag":"nemi_stock"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('vessa','hall','维莎·灰印','市政审计官','查过失踪议员的票据，却因证词未齐不能公开指控。','严苛、守程序','正式','案卷可以怀疑，证人不能随便牺牲。告诉我你掌握的证据。','[{"prompt":"一册账簿在听证前夜消失，封条却完整。","options":[{"label":"谁能开门？","reply":"带旧印的人能从侧面解开封条。","follow":"她让你比对旧印室门锁。","attitude":1,"flag":"hall_seal"},{"label":"能延期听证吗？","reply":"延期会让证人更危险。先给我一份副本。","follow":"她提供一张空白证物收据。","attitude":0,"flag":"hearing_deadline"},{"label":"这是你的疏忽。","reply":"责任在我，但指责填不了证据缺口。","follow":"她暂时不再提供钥匙。","attitude":-1,"flag":"vessa_cold"}]},{"prompt":"公开记录廊登记了每个进入大厅的访客。","options":[{"label":"查访客簿。","reply":"同一个名字在午夜重复两次，中间隔着一次钟鸣。","follow":"她展示墨迹深浅。","attitude":1,"flag":"double_entry"},{"label":"哪位官员最可疑？","reply":"我不会替你选嫌疑人，只能告诉你谁能签字。","follow":"她指出四个签章位置。","attitude":0,"flag":"four_seals"},{"label":"让我们直接拿走。","reply":"未经登记的证据进不了听证。","follow":"她挡在柜门前。","attitude":-1,"flag":"evidence_rule"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('orlan','hall','奥兰·石羽','城市档案保管员','将重要抄本拆成数份藏在城内，防止有人一次烧毁全部。','小心、爱用谜语','探询','纸张会烧，页码却能留在人的记忆里。','[{"prompt":"你找的页码不在这栋楼，封面的火痕是真的。","options":[{"label":"另一半在哪里？","reply":"去问高堂的修复师，她称过这本书。","follow":"他给你半片书脊。","attitude":1,"flag":"half_spine"},{"label":"为何不公开？","reply":"先公开不完整的书，会害真正的证人被指造假。","follow":"他写下找齐证据的顺序。","attitude":0,"flag":"archive_order"},{"label":"你藏了证据。","reply":"藏与保护，隔着一张没有名字的逮捕令。","follow":"他的回答更简短了。","attitude":-1,"flag":"orlan_guard"}]},{"prompt":"听证台后有一面回声墙。它记录不了声音，却会暴露敲钟时间。","options":[{"label":"怎么测量？","reply":"把铜杯放在第三块石板上，听回声的间隔。","follow":"他把铜杯交给你。","attitude":1,"flag":"echo_wall"},{"label":"谁造的？","reply":"是旧城工匠；新官员只学会盖章。","follow":"他指向石板上的匠人刻字。","attitude":0,"flag":"stone_mark"},{"label":"这能当证据吗？","reply":"与访客簿一起，才经得起质询。","follow":"他要求你带回两份记录。","attitude":0,"flag":"two_records"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('daran','hall','达兰·露桥','议会改革派联络员','希望听证公开，却受制于同僚的交易和旧债。','外向、擅长交涉','试探','大厅里没有纯粹的盟友，只有愿意先做正确事的人。','[{"prompt":"有人用紧急军令绕开了公开表决。","options":[{"label":"谁签了军令？","reply":"签名是真的，命令发布的时刻却不可能。","follow":"他把时间线记在你的地图上。","attitude":1,"flag":"false_time"},{"label":"能叫停吗？","reply":"先把城墙的原始换岗表送来。","follow":"他答应安排一次公开质询。","attitude":1,"flag":"public_question"},{"label":"你也投了赞成票。","reply":"我当时不知那份文书被换过。","follow":"他对你保持距离。","attitude":-1,"flag":"daran_vote"}]},{"prompt":"民众需要听见完整故事，不是半张证据。","options":[{"label":"我们可以公开证词。","reply":"那就保护证人，别只保护纸。","follow":"他安排旁听席。","attitude":1,"flag":"witness_seats"},{"label":"给我们钱买消息。","reply":"我只能给公开预算，不能用黑账。","follow":"他递来一份支出明细。","attitude":0,"flag":"public_budget"},{"label":"先替我们保密。","reply":"我会拖延会议，但不能永远拖。","follow":"他提出明确的时限。","attitude":0,"flag":"delay"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('kevan','walls','凯文·远炬','北段巡逻队长','丢了两名队员后仍每日亲自检查灯号。','谨慎、重视部下','怀疑外来者','站在这里能看见整个城市，也能看见它最不愿承认的缺口。','[{"prompt":"昨晚第五盏灯比第四盏先亮，是人为的。","options":[{"label":"谁能操控灯？","reply":"值夜人和传令官都有钥匙，只有一个有更换记录。","follow":"他给你一份排班副本。","attitude":1,"flag":"fifth_lamp"},{"label":"灯号意味着什么？","reply":"常规是撤回，倒序是让人打开暗门。","follow":"他指出城外坡道的盲区。","attitude":0,"flag":"reverse_signal"},{"label":"你在推卸责任。","reply":"我的责任是把剩下的人带回来。","follow":"他收起排班表。","attitude":-1,"flag":"kevan_distrust"}]},{"prompt":"军需仓少了四十支箭，却多了五十支无号箭。","options":[{"label":"有人换货？","reply":"是。箭羽来自城内的手艺，不是边境补给。","follow":"他让你保留一根样本。","attitude":1,"flag":"unmarked_arrow"},{"label":"会发动袭击吗？","reply":"有人想让它看起来像城外的人干的。","follow":"他提出巡逻配合。","attitude":1,"flag":"inside_threat"},{"label":"先封锁城墙。","reply":"封锁会把我的斥候困在外面。","follow":"他要求先数清失踪人数。","attitude":-1,"flag":"wall_block"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('riona','walls','瑞奥娜·盐脊','城墙排水技师','亲手修过暗门，因此知道官方图纸遗漏的通道。','务实、语速很快','忙碌','先别踩那块松砖。上回有人掉下去，还欠我一把扳手。','[{"prompt":"旧图纸只画了两道闸，地下还有第三道。","options":[{"label":"如何开启？","reply":"先关北端水轮，否则会被激流推回城内。","follow":"她画下水轮的位置。","attitude":1,"flag":"third_sluice"},{"label":"是谁建的？","reply":"比这届官员更早的工人，他们没有署名。","follow":"她找到未盖章的工票。","attitude":0,"flag":"old_workers"},{"label":"堵住不就好了？","reply":"堵了水会倒灌进酒馆后巷。","follow":"她要求先疏散居民。","attitude":-1,"flag":"flood_risk"}]},{"prompt":"泥里的靴印只有四道出去，五道进来。","options":[{"label":"第五个人去了哪？","reply":"向上的排风井，那里能通向军需仓。","follow":"她指给你带锈的爬梯。","attitude":1,"flag":"fifth_track"},{"label":"能测出时间吗？","reply":"泥还潮，应该在上一班巡逻之后。","follow":"她给出一个两小时窗口。","attitude":0,"flag":"mud_time"},{"label":"这只是野兽。","reply":"会拧开铁栅的野兽？我倒想见识。","follow":"她没打算陪你猜下去。","attitude":-1,"flag":"riona_doubt"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_npcs values('samir','walls','萨米尔·余烬','城防信号手','曾向外城发出正确警报，却被上级命令改成演习。','克制、记忆力强','渴望被听见','我不需要你相信我；只要你核对两份信号簿。','[{"prompt":"信号簿上把真实警报重写成一场演习。","options":[{"label":"原簿在哪里？","reply":"夹在灯塔铜镜背面，我不敢独自去取。","follow":"他交出开启镜框的小钥匙。","attitude":1,"flag":"mirror_key"},{"label":"谁命令改写？","reply":"公文来自大厅，但传令人从没露面。","follow":"他描述传令人鞋跟的缺口。","attitude":0,"flag":"messenger_heel"},{"label":"你也签了名。","reply":"我签了收件，不是认可内容。","follow":"他指出自己笔画的差别。","attitude":-1,"flag":"samir_signature"}]},{"prompt":"夜里听见的钟声比大厅钟声晚九息。","options":[{"label":"能证实吗？","reply":"每次都有同一段回声，去高台试试铜杯。","follow":"他让你记住节拍。","attitude":1,"flag":"nine_beats"},{"label":"城外也听得到？","reply":"只能听到第一声，第二声藏在墙里。","follow":"他画出墙体空腔。","attitude":0,"flag":"hollow_wall"},{"label":"这是幻术吗？","reply":"也许。但有人借它调动了真兵。","follow":"他请求保存士兵证词。","attitude":0,"flag":"real_orders"}]}]'::jsonb) on conflict(id) do update set name=excluded.name,role=excluded.role,background=excluded.background,personality=excluded.personality,attitude=excluded.attitude,intro=excluded.intro,topics=excluded.topics;
insert into public.uc_quests values('star','失窃的星盘','mara','kegs','追回失窃星盘的第五环，并查出谁在偷取灯号。','{"gold":24,"xp":55,"item":"刻度护符"}'::jsonb,'[{"area":"wonders","place":"封存柜","label":"核对星盘封存记录","text":"第五环不见了，入库单上的墨迹却比失窃时间更新。","skill":"调查","dc":12},{"area":"kegs","npc":"tobin","label":"询问伪造的入库笔迹","text":"托宾辨认出签名里故意模仿自己的倒钩。","skill":"洞悉","dc":12},{"area":"wonders","npc":"elric","label":"决定如何处置盗取零件的学徒","text":"学徒说她想用星盘证明父亲死于错误灯号。","options":[["交给审计官","留下公开证据，但学徒对你失去信任。","report"],["游说她归还零件","她愿交回第五环，并指出幕后买家。","persuade","说服",13],["收钱放她离开","你得到私下谢礼，却让星盘再次失踪。","bribe"]]},{"area":"wonders","place":"修复室","label":"修复并核对第五环","text":"零件上的刻线与城墙灯号完全吻合。","skill":"奥秘","dc":13},{"area":"kegs","npc":"mara","label":"向玛拉说明灯号真相","text":"玛拉联系证人，承诺让旧报告在酒馆被人听见。","options":[["公开记录","证人开始聚集，玛拉对你更加信任。","public"],["先保护证人","玛拉把楼上空房留给目击者。","protect"]]},{"area":"kegs","npc":"mara","label":"交付星盘委托","text":"玛拉结清委托，并把刻度护符交给你。","finish":true}]'::jsonb) on conflict(id) do update set name=excluded.name,description=excluded.description,reward=excluded.reward,stages=excluded.stages;
insert into public.uc_quests values('medicine','被换掉的药水','nemi','wonders','追查假药水流向，保护被当成嫌犯的送货少年。','{"gold":32,"xp":70,"item":"净化药剂"}'::jsonb,'[{"area":"kegs","place":"后巷的雨水槽","label":"检查后巷假药瓶","text":"瓶塞里卡着一缕蓝色布纤维。","skill":"察觉","dc":12},{"area":"wonders","npc":"nemi","label":"鉴别剩余药剂","text":"奈米发现染色剂来自公共水渠，而非诊所。","skill":"调查","dc":13},{"area":"kegs","npc":"sera","label":"决定少年的去向","text":"少年承认替人运货，却不知道箱里是假药。","options":[["交给守卫","瑟拉不赞同，但证词得到正式记录。","guard"],["游说他带路","他领你找到取货暗号，瑟拉感谢你。","guide","说服",13],["威吓逼供","他慌乱中说出军需仓名字，之后不愿再见你。","threat","威吓",13]]},{"area":"wonders","place":"修复室","label":"追踪封蜡来源","text":"蓝色封蜡由伪造公文的同一人购入。","skill":"调查","dc":14},{"area":"kegs","npc":"mara","label":"安排替换受害者手里的假药","text":"玛拉用酒馆的送餐路线悄悄更换药瓶。","options":[["先救病人","几名病人恢复了呼吸。","patients"],["先留一瓶作证","保留了能供审计官检测的证物。","sample"]]},{"area":"wonders","npc":"nemi","label":"向奈米交还证据","text":"奈米发放真正的药水，结清委托。","finish":true}]'::jsonb) on conflict(id) do update set name=excluded.name,description=excluded.description,reward=excluded.reward,stages=excluded.stages;
insert into public.uc_quests values('gate','城墙下的第二道门','ilya','wonders','调查失踪巡逻队，选择是否保护伊莉娅并争取她加入。','{"gold":45,"xp":100,"item":"夜巡长弓"}'::jsonb,'[{"area":"walls","place":"排水暗门","label":"辨认失踪小队的脚印","text":"一人仍活着，被迫从排风井上行。","skill":"求生","dc":14},{"area":"walls","npc":"riona","label":"安排排水暗门路线","text":"瑞奥娜会关掉水轮，为你争取一刻钟。","skill":"说服","dc":14},{"area":"kegs","npc":"tobin","label":"决定是否保护证人与伊莉娅","text":"有人递来一笔钱，要求你把伊莉娅的位置写在收据上。","options":[["拒绝并保护伊莉娅","托宾把藏身处交给你；伊莉娅愿与你并肩。","protect"],["收下钱换取情报","你得到路线，但伊莉娅不会把安全交给你。","sell"],["欺骗出钱的人","你套出幕后联系人，却没能取得伊莉娅的完全信任。","deceive","欺骗",15]]},{"area":"walls","place":"军需仓","label":"截住伪装成巡逻队的袭击者","text":"仓门被撬开，弓手占据高台，队长正准备焚毁报告。","skill":"察觉","dc":14},{"area":"walls","label":"击退暗门伏兵","text":"救出失踪队员，击败假巡逻队。","battle":"gate_ambush"},{"area":"wonders","npc":"ilya","label":"把失踪队员带回伊莉娅面前","text":"伊莉娅交出夜巡长弓，并决定是否成为队伍同伴。","finish":true,"recruitOutcome":"protect"}]'::jsonb) on conflict(id) do update set name=excluded.name,description=excluded.description,reward=excluded.reward,stages=excluded.stages;
insert into public.uc_quests values('ledger','听证席下的账簿','vessa','hall','找齐遭拆散的账簿，揭露谁在篡改公开听证。','{"gold":60,"xp":125,"item":"审计官胸针"}'::jsonb,'[{"area":"wonders","place":"修复室","label":"找回被剥掉的书脊","text":"书脊里有一串与听证席编号对应的刻痕。","skill":"调查","dc":15},{"area":"hall","npc":"orlan","label":"说服保管员交出抄本","text":"奥兰要求先保证证人可以安全离开。","skill":"说服","dc":15},{"area":"kegs","npc":"mara","label":"选择公布证据的方式","text":"酒馆已经聚集证人，门外却有带刀的人在记名字。","options":[["秘密护送证人","证人避开了耳目，记录更难质疑。","escort"],["即刻公开证据","民众聚集，但袭击者也知道了位置。","publish"],["欺骗监视者","监视者追逐假账簿，你赢得准备时间。","decoy","欺骗",15]]},{"area":"hall","place":"旧印室","label":"比对真正的旧印","text":"真正的印章上有一道细裂痕，伪造品没有。","skill":"调查","dc":16},{"area":"hall","label":"阻止焚毁听证账簿","text":"持火油的人封锁了记录廊，袭击者要烧掉最后的签名。","battle":"ledger_fire"},{"area":"hall","npc":"vessa","label":"交付完整账簿","text":"维莎当众封存证据并支付委托报酬。","finish":true}]'::jsonb) on conflict(id) do update set name=excluded.name,description=excluded.description,reward=excluded.reward,stages=excluded.stages;
insert into public.uc_quests values('signal','错误的第十三声','kevan','walls','调查假军令与钟声，阻止城防被用于制造冲突。','{"gold":52,"xp":110,"item":"信号手戒指"}'::jsonb,'[{"area":"walls","place":"北段瞭望台","label":"记录倒序灯号","text":"信号的起始时刻被提前了九息。","skill":"察觉","dc":15},{"area":"hall","npc":"daran","label":"核对紧急军令","text":"达兰拿出投票记录，军令竟早于表决。","skill":"洞悉","dc":15},{"area":"walls","npc":"samir","label":"决定如何保护信号手","text":"萨米尔愿意作证，却担心城墙上的同袍遭到连坐。","options":[["保护信号手与同袍","萨米尔交出原始信号簿。","protect"],["先公开他的名字","证词更快传开，部分士兵责怪你的鲁莽。","reveal"],["游说他匿名作证","他接受匿名质询，留下可验证的节拍。","anonymous","说服",16]]},{"area":"hall","place":"议事高台","label":"测量第二道钟声","text":"回声与铜杯共振，证实钟声藏在墙里。","skill":"奥秘","dc":16},{"area":"walls","place":"军需仓","label":"截获传令人的新命令","text":"命令要求把北段守卫调去无人的南门。","skill":"潜行","dc":16},{"area":"walls","npc":"kevan","label":"交还原始信号簿","text":"凯文停止错误调度，结清委托，后续仍守在城墙。","finish":true}]'::jsonb) on conflict(id) do update set name=excluded.name,description=excluded.description,reward=excluded.reward,stages=excluded.stages;
insert into public.uc_battles values('gate_ambush','暗门假巡逻队','火把从排风井落下；失踪队员被绑在通向军需仓的铁梯上。','[["伪巡逻队长",48,16,5,4,7,"号令：每回合为友军增强攻势"],["暗门重甲兵",38,15,4,3,7,"格挡：护甲较高"],["暗门重甲兵",38,15,4,3,7,"格挡：护甲较高"],["高台弩手",30,14,5,4,6,"齐射：优先瞄准后排"]]'::jsonb) on conflict(id) do update set name=excluded.name,intro=excluded.intro,foes=excluded.foes;
insert into public.uc_battles values('ledger_fire','记录廊焚证者','焚证术士以火油封门，铁卫和刀客分两路压向证人。','[["焚证术士",52,16,6,5,8,"火油：攻击时造成更高伤害"],["护卷铁卫",46,17,5,4,7,"钢盾：护甲较高"],["侧廊刀客",36,15,6,4,7,"突袭：命中较高"],["火油投手",32,14,5,5,7,"投火：伤害较高"]]'::jsonb) on conflict(id) do update set name=excluded.name,intro=excluded.intro,foes=excluded.foes;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('修复师短剑','wonders',0,'weapon',22,1,2,0,'普通','轻巧的修复工刀，攻击 +1，伤害 +2。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('高堂护胸','wonders',0,'armor',36,0,0,2,'精良','分层铜片护胸，AC +2。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('刻度护符','wonders',0,'offhand',40,1,0,0,'精良','星盘刻度制成，攻击 +1。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('银线药水','wonders',0,'consumable',18,0,0,0,'普通','饮用恢复 14 HP。','heal') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('护盾卷轴','wonders',0,'consumable',24,0,0,0,'精良','使用后下一次受攻击 AC +4。','ward') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('星火卷轴','wonders',0,'consumable',28,0,0,0,'精良','战斗中以法术攻击造成 12–18 伤害。','damage') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('净化药剂','wonders',5,'consumable',30,0,0,0,'精良','恢复 20 HP 并清除倒地状态。','heal20') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('夜巡长弓','wonders',10,'weapon',70,2,5,0,'稀有','伊莉娅设计的弓，攻击 +2，伤害 +5。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('审计官胸针','wonders',10,'offhand',65,0,0,2,'稀有','经过符文加固的徽章，AC +2。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('军令破咒卷轴','wonders',10,'consumable',52,0,0,0,'稀有','战斗中以法术攻击造成 20–26 伤害。','damage20') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('信号手戒指','wonders',15,'offhand',90,2,0,1,'稀有','校准过的传讯戒，攻击 +2，AC +1。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('拱顶秘银剑','wonders',20,'weapon',145,4,7,0,'史诗','稀少的秘银之刃，攻击 +4，伤害 +7。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
insert into public.campaign_items(name,merchant,unlock_chapter,slot,price,attack,damage,ac,rarity,description,effect) values('奇迹高堂守护甲','wonders',25,'armor',170,0,0,4,'史诗','限量符文重甲，AC +4。','') on conflict(name) do update set merchant=excluded.merchant,unlock_chapter=excluded.unlock_chapter,slot=excluded.slot,price=excluded.price,attack=excluded.attack,damage=excluded.damage,ac=excluded.ac,rarity=excluded.rarity,description=excluded.description,effect=excluded.effect;
create or replace function public.campaign_remove_one(p_bag jsonb,p_name text) returns jsonb language sql immutable set search_path=public,pg_temp as $$ select coalesce(jsonb_agg(value order by ord) filter(where ord<>(select min(n) from jsonb_array_elements_text(p_bag) with ordinality x(v,n) where v=p_name)),'[]'::jsonb) from jsonb_array_elements(p_bag) with ordinality x(value,ord) $$;
revoke all on function public.campaign_remove_one(jsonb,text) from public,anon,authenticated;
create or replace function public.party_snapshot(p_code text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
 if auth.uid() is null or not exists(select 1 from public.players where room_code=upper(p_code) and user_id=auth.uid()) then raise exception 'NOT_MEMBER'; end if;
 select jsonb_build_object('room',r.code,'players',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'class_name',p.class_name,'is_host',p.is_host,'is_ready',p.is_ready,'hp',p.hp,'max_hp',p.max_hp,'ac',p.ac,'stats',p.stats,'inventory',p.inventory,'equipment',p.equipment,'gold',p.gold,'death_failures',p.death_failures,'death_successes',p.death_successes,'last_seen',p.last_seen,'level',p.level,'spell_slots',p.spell_slots,'ability_charges',p.ability_charges,'is_companion',p.is_companion,'experience',p.experience) order by p.created_at) from public.players p where p.room_code=r.code and (p.user_id is not null or p.is_companion)),'[]'::jsonb),'me',(select p.id from public.players p where p.room_code=r.code and p.user_id=auth.uid()),'state',coalesce(g.state,'{}'::jsonb),'messages',coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from (select id,sender,body,kind,created_at from public.messages where room_code=r.code order by id desc limit 100) m),'[]'::jsonb)) into result from public.rooms r left join public.game_states g on g.room_code=r.code where r.code=upper(p_code);
 return result;
end $$;
create or replace function public.campaign_finish_turn(p_code text,p_combat jsonb,p_actor bigint) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_combat jsonb:=p_combat; v_ord bigint; v_next bigint; v_foe jsonb; v_target public.players%rowtype; v_roll int; v_dmg int; v_log text:=''; v_ward int;
begin
 if public.campaign_enemy_hp(v_combat->'enemies')=0 then
   update public.players set gold=gold+12+coalesce((select (state->>'chapter')::int/5 from public.game_states where room_code=p_code),0)*3 where room_code=p_code and user_id is not null;
   return jsonb_build_object('combat',v_combat,'log','；敌方全灭，队员获得战利品金币');
 end if;
 select ord into v_ord from jsonb_array_elements(v_combat->'initiative') with ordinality e(item,ord) where (item->>'id')::bigint=p_actor;
 select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality e(item,ord) join public.players p on p.id=(item->>'id')::bigint where e.ord>v_ord and p.hp>0 and p.death_failures<3 order by e.ord limit 1;
 if v_next is null then
   for v_foe in select value from jsonb_array_elements(v_combat->'enemies') where (value->>'hp')::int>0 loop
     select * into v_target from public.players where room_code=p_code and (user_id is not null or is_companion) and hp>0 and death_failures<3 order by case when (v_foe->>'special') like '齐射%' then ac else floor(random()*20)::int end limit 1;
     exit when not found;
     v_roll:=floor(random()*20)::int+1;
     v_ward:=coalesce((v_combat->'wards'->>v_target.id::text)::int,0);
     if v_roll=20 or (v_roll<>1 and v_roll+(v_foe->>'attack_bonus')::int>=v_target.ac+v_ward) then
       v_dmg:=floor(random()*(v_foe->>'damage_die')::int)::int+(v_foe->>'damage_min')::int+case when (v_foe->>'special') like '火油%' or (v_foe->>'special') like '投火%' then 2 else 0 end;
       update public.players set hp=greatest(0,hp-v_dmg) where id=v_target.id;
       v_log:=v_log||'；'||(v_foe->>'name')||case when v_foe ? 'special' then '〔'||(v_foe->>'special')||'〕' else '' end||'攻击'||v_target.name||'，伤害 '||v_dmg;
     else v_log:=v_log||'；'||(v_foe->>'name')||'未命中'; end if;
     v_combat:=jsonb_set(v_combat,'{wards}',coalesce(v_combat->'wards','{}'::jsonb)-v_target.id::text);
   end loop;
   select p.id into v_next from jsonb_array_elements(v_combat->'initiative') with ordinality e(item,ord) join public.players p on p.id=(item->>'id')::bigint where p.hp>0 and p.death_failures<3 order by e.ord limit 1;
   v_combat:=jsonb_set(v_combat,'{round}',to_jsonb((v_combat->>'round')::int+1));
 end if;
 v_combat:=jsonb_set(v_combat,'{turn}',coalesce(to_jsonb(v_next),'null'::jsonb));
 if v_next is null then v_log:=v_log||'；队伍全员倒地'; end if;
 return jsonb_build_object('combat',v_combat,'log',v_log);
end $$;
create or replace function public.party_command(p_code text, p_action text, p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_name text; v_class text; v_id bigint; v_host boolean; v_state jsonb; v_players int; v_unready int; v_target bigint; v_roll int; v_bonus int; v_dc int; v_dmg int; v_hp int; v_ac int; v_idx int; v_flags jsonb; v_clues jsonb; v_combat jsonb; v_turn bigint; v_next bigint; v_enemy_hp int; v_log text; v_chars text:='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; v_rand bytea; v_try int; v_newcode text; v_stats jsonb; v_max int; v_init jsonb; v_ord bigint; v_scene jsonb; v_key text; v_skill text; v_enemy jsonb; v_aid boolean; v_choice jsonb; v_beat jsonb; v_step int; v_dialogue jsonb; v_item public.campaign_items%rowtype; v_old public.campaign_items%rowtype; v_equipped text; v_foe jsonb; v_enemies jsonb; v_result jsonb; v_chapter int; v_price int;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 if p_action='create' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人','圣武士') then raise exception 'INVALID_CHARACTER'; end if;
  for v_try in 1..10 loop
   v_rand:=decode(replace(gen_random_uuid()::text,'-',''),'hex'); v_newcode:='';
   for v_idx in 0..4 loop v_newcode:=v_newcode||substr(v_chars,1+get_byte(v_rand,v_idx)%length(v_chars),1); end loop;
   insert into public.rooms(code) values(v_newcode) on conflict do nothing;
   exit when found;
  end loop;
  if v_try=10 and not found then raise exception 'CODE_EXHAUSTED'; end if;
  v_code:=v_newcode;
  perform public.party_character(v_code,v_uid,v_name,v_class,true);
  insert into public.game_states(room_code,state) values(v_code,jsonb_build_object('started',false,'chapter',0,'flags','[]'::jsonb,'clues','[]'::jsonb,'quest','追查消失的议员','completed_quests','[]'::jsonb,'combat',null,'version',1,'ending',null));
  return public.party_snapshot(v_code);
 end if;
 if p_action='join' then
  v_name:=left(trim(coalesce(p_payload->>'name','')),32); v_class:=p_payload->>'class';
  if length(v_name)<2 or v_class not in ('战士','游荡者','法师','牧师','游侠','吟游诗人','圣武士') then raise exception 'INVALID_CHARACTER'; end if;
  perform 1 from public.rooms where code=v_code for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if exists(select 1 from public.game_states where room_code=v_code and (state->>'started')::boolean) then raise exception 'GAME_STARTED'; end if;
  if exists(select 1 from public.players where room_code=v_code and user_id=v_uid) then return public.party_snapshot(v_code); end if;
  select count(*) into v_players from public.players where room_code=v_code and user_id is not null;
  if v_players>=5 then raise exception 'ROOM_FULL'; end if;
  perform public.party_character(v_code,v_uid,v_name,v_class,false);
  return public.party_snapshot(v_code);
 end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select id,name,is_host,hp,ac into v_id,v_name,v_host,v_hp,v_ac from public.players where room_code=v_code and user_id=v_uid;
 if v_id is null then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if p_action='heartbeat' then update public.players set last_seen=now() where id=v_id; return public.party_snapshot(v_code); end if;
 if p_action='leave' then
  delete from public.players where id=v_id;
  if v_host then update public.players set is_host=true,is_ready=false where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1); end if;
  return jsonb_build_object('left',true);
 end if;
 if p_action='claim_host' then
  if not exists(select 1 from public.players where room_code=v_code and is_host and user_id is not null and last_seen>now()-interval '5 minutes') then
   update public.players set is_host=false where room_code=v_code;
   update public.players set is_host=true where id=(select id from public.players where room_code=v_code and user_id is not null order by created_at,id limit 1);
  end if;
  return public.party_snapshot(v_code);
 end if;
 if p_action='ready' then
  if (v_state->>'started')::boolean then raise exception 'ALREADY_STARTED'; end if;
  update public.players set is_ready=not is_ready where id=v_id;
 elsif p_action='start' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  select count(*),count(*) filter(where not is_ready) into v_players,v_unready from public.players where room_code=v_code and user_id is not null;
  if v_players<2 or v_players>5 or v_unready>0 then raise exception 'PARTY_NOT_READY'; end if;
  v_state:=jsonb_set(v_state,'{started}','true'::jsonb);
  v_log:='冒险开始。';
 elsif p_action='chat' then
  v_log:=left(trim(coalesce(p_payload->>'body','')),500);
  if length(v_log)<1 then raise exception 'EMPTY_MESSAGE'; end if;
 elsif p_action='roll' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  -- The browser chooses a skill and DC; the modifier comes from the authenticated character.
  if p_payload->>'skill' not in ('调查','洞悉','说服','潜行','运动','奥秘','求生') then raise exception 'INVALID_SKILL'; end if;
  select floor(((stats->>case p_payload->>'skill' when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 else 5 end)::int-10)/2.0)::int
    + case when (class_name='战士' and p_payload->>'skill'='运动') or (class_name='游荡者' and p_payload->>'skill' in ('调查','潜行')) or (class_name='法师' and p_payload->>'skill'='奥秘') or (class_name='牧师' and p_payload->>'skill'='洞悉') or (class_name='游侠' and p_payload->>'skill'='求生') or (class_name='吟游诗人' and p_payload->>'skill'='说服') or (class_name='圣武士' and p_payload->>'skill' in ('运动','说服')) then 2 else 0 end into v_bonus from public.players where id=v_id;
  v_dc:=greatest(5,least(30,coalesce((p_payload->>'dc')::int,15)));
  v_roll:=floor(random()*20)::int+1;
  v_log:=left(coalesce(p_payload->>'skill','技能'),30)||'检定 D20='||v_roll||'，加值 '||v_bonus||'，DC '||v_dc||'：'||case when v_roll=20 then '大成功' when v_roll=1 then '大失败' when v_roll+v_bonus>=v_dc then '成功' else '失败' end;
 elsif p_action='dialogue' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_chapter:=(v_state->>'chapter')::int;
  v_step:=case when (v_state#>>'{dialogue,chapter}')::int=v_chapter then coalesce((v_state#>>'{dialogue,step}')::int,0) else 0 end;
  select beats->v_step into v_beat from public.campaign_dialogues where chapter_id=v_chapter;
  if v_beat is null then raise exception 'DIALOGUE_COMPLETE'; end if;
  v_idx:=coalesce((p_payload->>'choice')::int,-1);
  if v_idx not in (0,1) then raise exception 'INVALID_DIALOGUE_CHOICE'; end if;
  v_choice:=v_beat->'options'->v_idx;
  v_flags:=coalesce(v_state->'flags','[]'::jsonb);
  if not v_flags ? (v_choice->>'flag') then v_flags:=v_flags||to_jsonb(v_choice->>'flag'); end if;
  v_state:=jsonb_set(v_state,'{flags}',v_flags);
  v_dialogue:=case when v_step=0 then jsonb_build_object('chapter',v_chapter,'step',1,'history',jsonb_build_array(jsonb_build_object('choice',v_choice->>'label','reply',v_choice->>'reply'))) else jsonb_set(jsonb_set(v_state->'dialogue','{step}',to_jsonb(v_step+1)),'{history}',coalesce(v_state#>'{dialogue,history}','[]'::jsonb)||jsonb_build_array(jsonb_build_object('choice',v_choice->>'label','reply',v_choice->>'reply'))) end;
  v_state:=jsonb_set(v_state,'{dialogue}',v_dialogue);
  v_log:=(v_choice->>'label')||' — '||(v_choice->>'reply');
 elsif p_action='explore' then
  if coalesce((v_state#>>'{dialogue,chapter}')::int,-1)<>(v_state->>'chapter')::int or coalesce((v_state#>>'{dialogue,step}')::int,0)<3 then raise exception 'DIALOGUE_FIRST'; end if;
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_idx:=coalesce((p_payload->>'index')::int,-1);
  if v_idx<0 or v_idx>1 then raise exception 'INVALID_ENCOUNTER'; end if;
  v_key:=(v_state->>'chapter')||':'||v_idx;
  if coalesce(v_state->'explored','[]'::jsonb) ? v_key then raise exception 'ALREADY_EXPLORED'; end if;
  select scenes->v_idx into v_scene from public.campaign_chapters where id=(v_state->>'chapter')::int;
  if v_scene is null then raise exception 'ENCOUNTER_UNAVAILABLE'; end if;
  v_skill:=v_scene->>'skill'; v_dc:=(v_scene->>'dc')::int;
  select floor(((stats->>case v_skill when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 else 5 end)::int-10)/2.0)::int
   + case when (class_name='战士' and v_skill='运动') or (class_name='游荡者' and v_skill in ('调查','潜行')) or (class_name='法师' and v_skill='奥秘') or (class_name='牧师' and v_skill='洞悉') or (class_name='游侠' and v_skill='求生') or (class_name='吟游诗人' and v_skill='说服') or (class_name='圣武士' and v_skill in ('运动','说服')) then 2 else 0 end into v_bonus from public.players where id=v_id;
  v_roll:=floor(random()*20)::int+1;
  v_state:=jsonb_set(v_state,'{explored}',coalesce(v_state->'explored','[]'::jsonb)||to_jsonb(v_key));
  if v_roll=20 or (v_roll<>1 and v_roll+v_bonus>=v_dc) then
   v_clues:=coalesce(v_state->'clues','[]'::jsonb); v_flags:=coalesce(v_state->'flags','[]'::jsonb);
   if not v_clues ? (v_scene->>'clue') then v_clues:=v_clues||to_jsonb(v_scene->>'clue'); end if;
   if not v_flags ? (v_scene->>'flag') then v_flags:=v_flags||to_jsonb(v_scene->>'flag'); end if;
   v_state:=jsonb_set(jsonb_set(v_state,'{clues}',v_clues),'{flags}',v_flags);
   v_log:=v_scene->>'success';
  else v_log:=v_scene->>'failure'; end if;
  v_log:=(v_scene->>'label')||' · '||v_skill||' D20='||v_roll||'+'||v_bonus||' / DC '||v_dc||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'：'||v_log;
 elsif p_action='choice' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)=(v_state->>'chapter')::int then raise exception 'CHOICE_ALREADY_MADE'; end if;
  if not (coalesce(v_state->'explored','[]'::jsonb) ? ((v_state->>'chapter')||':0')) or not (coalesce(v_state->'explored','[]'::jsonb) ? ((v_state->>'chapter')||':1')) then raise exception 'EXPLORE_BEFORE_CHOICE'; end if;
  v_idx:=coalesce((p_payload->>'index')::int,-1);
  if v_idx<0 or v_idx>1 then raise exception 'INVALID_CHOICE'; end if;
  select choices->v_idx into p_payload from public.campaign_chapters where id=(v_state->>'chapter')::int;
  if p_payload is null then raise exception 'INVALID_CHOICE'; end if;
  v_flags:=coalesce(v_state->'flags','[]'::jsonb); v_clues:=coalesce(v_state->'clues','[]'::jsonb);
  if length(coalesce(p_payload->>'flag',''))>0 and not v_flags ? (p_payload->>'flag') then v_flags:=v_flags||to_jsonb(left(p_payload->>'flag',40)); end if;
  if length(coalesce(p_payload->>'clue',''))>0 and not v_clues ? (p_payload->>'clue') then v_clues:=v_clues||to_jsonb(left(p_payload->>'clue',60)); end if;
  v_state:=jsonb_set(jsonb_set(v_state,'{flags}',v_flags),'{clues}',v_clues);
  v_state:=jsonb_set(v_state,'{chosen_chapter}',to_jsonb((v_state->>'chapter')::int));
  if (v_state->>'chapter')::int=29 then v_state:=jsonb_set(v_state,'{ending}',to_jsonb(case when (v_state->'flags') ? 'council' then '公民议会重建' when (v_state->'flags') ? 'autonomy' then '地下自治联盟' when (select count(*) from jsonb_array_elements_text(v_state->'flags') f where f not like 'voice_%' and f not like 'approach_%' and f not like 'support_%')>=18 then '城市共同体' else '艰难的黎明' end)); end if;
  v_log:='选择：'||left(coalesce(p_payload->>'label',''),80);
 elsif p_action='advance' then
  if not v_host then raise exception 'HOST_ONLY'; end if;
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if (v_state->>'chapter')::int>=29 then raise exception 'CAMPAIGN_COMPLETE'; end if;
  if coalesce((v_state->>'chosen_chapter')::int,-1)<>coalesce((v_state->>'chapter')::int,0) then raise exception 'CHOOSE_BEFORE_ADVANCE'; end if;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and coalesce((v_state#>>'{combat,hp}')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
  v_idx:=least(29,coalesce((v_state->>'chapter')::int,0)+1);
  v_state:=jsonb_set(jsonb_set(v_state,'{chapter}',to_jsonb(v_idx)),'{completed_quests}',coalesce(v_state->'completed_quests','[]'::jsonb)||to_jsonb(v_idx-1));
  -- Story milestones grant levels and spell circles to every member atomically.
  update public.players set max_hp=max_hp+(public.campaign_level(v_idx)-level)*case class_name when '战士' then 6 when '圣武士' then 6 when '法师' then 4 else 5 end,
    hp=hp+(public.campaign_level(v_idx)-level)*case class_name when '战士' then 6 when '圣武士' then 6 when '法师' then 4 else 5 end,
    level=public.campaign_level(v_idx),spell_slots=public.campaign_slots(public.campaign_level(v_idx)),ability_charges=2
    where room_code=v_code and (user_id is not null or is_companion) and level<public.campaign_level(v_idx);
  -- A completed fight grants a camp rest before the next scene. Downed allies need healing first.
  if coalesce((v_state#>>'{combat,hp}')::int,-1)=0 then
   update public.players set hp=max_hp,spell_slots=public.campaign_slots(level),ability_charges=2 where room_code=v_code and (user_id is not null or is_companion) and hp>0;
  end if;
  select details into v_enemy from public.campaign_battles where chapter_id=v_idx;
  if v_enemy is not null then
   select count(*) into v_players from public.players where room_code=v_code and user_id is not null;
   v_aid:=coalesce(v_state->'flags','[]'::jsonb) ? (v_enemy->>'aid');
   v_enemy_hp:=(v_enemy->>'hp')::int+greatest(0,v_players-2)*7-case when v_aid then 5 else 0 end;
   select jsonb_agg(jsonb_build_object('id',id,'roll',roll) order by roll desc,id),(array_agg(id order by roll desc,id))[1] into v_init,v_turn from (select id,floor(random()*20)::int+1 as roll from public.players where room_code=v_code and (user_id is not null or is_companion) and hp>0) i;
   v_enemies:='[]'::jsonb;
   for v_foe in select value from jsonb_array_elements(coalesce(v_enemy->'foes',jsonb_build_array(v_enemy))) loop
     v_enemy_hp:=(v_foe->>'hp')::int+greatest(0,v_players-2)*6-case when v_aid then 3 else 0 end;
     v_enemies:=v_enemies||jsonb_build_array(jsonb_build_object('name',v_foe->>'name','hp',v_enemy_hp,'max_hp',v_enemy_hp,'ac',(v_foe->>'ac')::int-case when v_aid then 1 else 0 end,'attack_bonus',(v_foe->>'attack')::int,'damage_min',(v_foe->>'min')::int,'damage_die',(v_foe->>'die')::int));
   end loop;
   v_state:=jsonb_set(v_state,'{combat}',jsonb_build_object('name',v_enemy->>'name','enemies',v_enemies,'hp',public.campaign_enemy_hp(v_enemies),'max_hp',public.campaign_enemy_hp(v_enemies),'turn',v_turn,'initiative',v_init,'round',1,'wards','{}'::jsonb));
  else v_state:=jsonb_set(v_state,'{combat}','null'::jsonb); end if;
  if v_idx=10 then v_log:='新区域已解锁：至高大厅。'; elsif v_idx=15 then v_log:='新区域已解锁：上城区城墙。'; end if;
  if v_idx%5=0 then update public.players set gold=gold+10 where room_code=v_code and user_id is not null; end if;
  v_log:=coalesce(v_log,'')||' 推进至第 '||(v_idx+1)||' 章。'||case when v_idx%5=0 then ' 队员各获 10 金币。' else '' end||case when v_enemy is not null then ' 遭遇：'||(v_enemy->>'name')||'。'||case when v_aid then v_enemy->>'aidText' else '' end else '' end;
 elsif p_action='attack' then
  v_combat:=v_state->'combat';
  if v_combat is null or v_combat='null'::jsonb or (v_combat->>'hp')::int<=0 then raise exception 'NO_COMBAT'; end if;
  if (v_combat->>'turn')::bigint<>v_id then raise exception 'NOT_YOUR_TURN'; end if;
  if v_hp<=0 then raise exception 'DOWNED'; end if;
  v_idx:=coalesce((p_payload->>'enemy')::int,-1);
  if v_idx<0 or v_idx>=jsonb_array_length(v_combat->'enemies') then raise exception 'INVALID_ENEMY'; end if;
  v_foe:=v_combat->'enemies'->v_idx;
  if (v_foe->>'hp')::int<=0 then raise exception 'ENEMY_DOWN'; end if;
  select case class_name when '战士' then 5 when '游荡者' then 5 when '法师' then 5 when '游侠' then 5 when '圣武士' then 5 else 4 end+(level-1)/4 into v_bonus from public.players where id=v_id;
  select coalesce(max(i.attack),0),coalesce(max(i.damage),0) into v_dc,v_max from public.players p cross join lateral jsonb_array_elements_text(p.equipment) e(name) join public.campaign_items i on i.name=e.name and i.slot='weapon' where p.id=v_id;
  v_bonus:=v_bonus+v_dc;
  v_roll:=floor(random()*20)::int+1;
  v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_foe->>'ac')::int) then 0 else floor(random()*8)::int+1+v_bonus+v_max+case when v_roll=20 then floor(random()*8)::int+1 else 0 end end;
  v_enemy_hp:=greatest(0,(v_foe->>'hp')::int-v_dmg);
  v_combat:=jsonb_set(v_combat,array['enemies',v_idx::text,'hp'],to_jsonb(v_enemy_hp));
  v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(public.campaign_enemy_hp(v_combat->'enemies')));
  v_log:='攻击 '||(v_foe->>'name')||' D20='||v_roll||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'，伤害 '||v_dmg;
  v_result:=public.campaign_finish_turn(v_code,v_combat,v_id);
  v_state:=jsonb_set(v_state,'{combat}',v_result->'combat');
  v_log:=v_log||coalesce(v_result->>'log','');
 elsif p_action='heal' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  v_target:=coalesce((p_payload->>'target')::bigint,v_id);
  if not exists(select 1 from public.players where id=v_target and room_code=v_code and (user_id is not null or is_companion)) then raise exception 'INVALID_TARGET'; end if;
  if not (select inventory ? '治疗药水' from public.players where id=v_id) then raise exception 'NO_POTION'; end if;
  update public.players set inventory=public.campaign_remove_one(inventory,'治疗药水') where id=v_id;
  update public.players set hp=least(max_hp,hp+8),death_failures=0,death_successes=0 where id=v_target and hp>=0;
  if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_target)); end if;
  v_log:='使用治疗药水，恢复 8 HP。';
 elsif p_action='buy' then
  if not (v_state->>'started')::boolean then raise exception 'NOT_STARTED'; end if;
  if coalesce((v_state#>>'{combat,hp}')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
  select * into v_item from public.campaign_items where name=p_payload->>'item' and unlock_chapter<=(v_state->>'chapter')::int;
  if not found then raise exception 'ITEM_LOCKED'; end if;
  if v_item.slot<>'consumable' and (select inventory ? v_item.name or equipment ? v_item.name from public.players where id=v_id) then raise exception 'ALREADY_OWNED'; end if;
  v_price:=case when coalesce(v_state->'flags','[]'::jsonb) ? ('support_'||(v_state->>'chapter')||'_stay') then ceil(v_item.price*0.9)::int else v_item.price end;
  update public.players set gold=gold-v_price,inventory=inventory||to_jsonb(v_item.name) where id=v_id and gold>=v_price;
  if not found then raise exception 'NOT_ENOUGH_GOLD'; end if;
  v_log:='从'||v_item.merchant||'购买'||v_item.name||'，花费 '||v_price||' 金币。';
 elsif p_action='equip' then
  if coalesce((v_state#>>'{combat,hp}')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
  select * into v_item from public.campaign_items where name=p_payload->>'item' and slot<>'consumable';
  if not found or not (select inventory ? v_item.name from public.players where id=v_id) then raise exception 'ITEM_NOT_IN_BAG'; end if;
  select e.name into v_equipped from public.players p cross join lateral jsonb_array_elements_text(p.equipment) e(name) left join public.campaign_items old_item on old_item.name=e.name where p.id=v_id and (old_item.slot=v_item.slot or (e.name='基础武器' and v_item.slot='weapon')) limit 1;
  select * into v_old from public.campaign_items where name=v_equipped;
  update public.players set inventory=(inventory-v_item.name)||case when v_equipped is not null and v_equipped<>'基础武器' then to_jsonb(v_equipped) else '[]'::jsonb end,
    equipment=(equipment-coalesce(v_equipped,''))||to_jsonb(v_item.name),ac=ac-coalesce(v_old.ac,0)+v_item.ac where id=v_id;
  v_log:='装备'||v_item.name||case when v_item.ac>0 then '，AC +'||v_item.ac else '，攻击 +'||v_item.attack||'、伤害 +'||v_item.damage end;
 elsif p_action='death_save' then
  if v_hp<>0 then raise exception 'NOT_DOWNED'; end if;
  v_roll:=floor(random()*20)::int+1;
  if v_roll=20 then update public.players set hp=1,death_failures=0,death_successes=0 where id=v_id;
   if v_state->'combat' is not null and v_state->'combat'<>'null'::jsonb and v_state#>'{combat,turn}'='null'::jsonb then v_state:=jsonb_set(v_state,'{combat,turn}',to_jsonb(v_id)); end if;
  elsif v_roll=1 then update public.players set death_failures=least(3,death_failures+2) where id=v_id;
  elsif v_roll>=10 then update public.players set death_successes=least(3,death_successes+1) where id=v_id;
  else update public.players set death_failures=least(3,death_failures+1) where id=v_id; end if;
  v_log:='死亡豁免 D20='||v_roll||case when v_roll=20 then '，恢复 1 HP' else '' end;
 else raise exception 'UNKNOWN_ACTION'; end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 if v_log is not null then insert into public.messages(room_code,sender,body,kind) values(v_code,v_name,v_log,p_action); end if;
 return public.party_snapshot(v_code);
end $$;
create or replace function public.party_power(p_code text,p_id text,p_target bigint default null,p_slot integer default 0)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_actor public.players%rowtype; v_target public.players%rowtype;
 v_state jsonb; v_combat jsonb; v_power public.campaign_powers%rowtype; v_slots jsonb; v_slot integer:=coalesce(p_slot,0); v_roll integer; v_bonus integer; v_amount integer;
 v_hp integer; v_next bigint; v_ord bigint; v_dmg integer; v_log text; v_stat integer; v_warr integer; v_idx integer; v_foe jsonb; v_result jsonb;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select * into v_actor from public.players where room_code=v_code and user_id=v_uid;
 if not found then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if not coalesce((v_state->>'started')::boolean,false) then raise exception 'NOT_STARTED'; end if;
 v_combat:=v_state->'combat';
 if p_id='rest' then
   if not v_actor.is_host then raise exception 'HOST_ONLY'; end if;
   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>0 then raise exception 'COMBAT_ACTIVE'; end if;
   if coalesce((v_state->>'rested_chapter')::int,-1)=(v_state->>'chapter')::int then raise exception 'ALREADY_RESTED'; end if;
   update public.players set hp=max_hp,death_failures=0,death_successes=0,spell_slots=public.campaign_slots(level),ability_charges=2
    where room_code=v_code and user_id is not null and death_failures<3;
   v_state:=jsonb_set(v_state,'{rested_chapter}',to_jsonb((v_state->>'chapter')::int));
   v_log:='队伍长休：恢复生命、职业技能和法术位（本章限一次）。';
 else
   select * into v_power from public.campaign_powers where id=p_id and profession=v_actor.class_name;
   if not found then raise exception 'POWER_NOT_KNOWN'; end if;
   if v_actor.hp<=0 or v_actor.death_failures>=3 then raise exception 'DOWNED'; end if;
   if v_power.ring=0 then
     if v_slot<>0 or v_actor.ability_charges<=0 then raise exception 'NO_ABILITY_CHARGES'; end if;
     update public.players set ability_charges=ability_charges-1 where id=v_actor.id;
   else
     if v_slot<v_power.ring or v_slot>6 or v_actor.level<2*v_power.ring-1 then raise exception 'SPELL_CIRCLE_LOCKED'; end if;
     v_slots:=v_actor.spell_slots;
     if coalesce((v_slots->>v_slot)::int,0)<=0 then raise exception 'NO_SPELL_SLOT'; end if;
     update public.players set spell_slots=jsonb_set(spell_slots,array[v_slot::text],to_jsonb((v_slots->>v_slot)::int-1)) where id=v_actor.id;
   end if;
   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>0 then
     if (v_combat->>'turn')::bigint<>v_actor.id then raise exception 'NOT_YOUR_TURN'; end if;
   elsif v_power.kind<>'heal' then raise exception 'NO_COMBAT'; end if;
   v_amount:=v_power.amount+greatest(0,v_slot-v_power.ring)*2;
   if v_power.kind in ('heal','ward') then
     select * into v_target from public.players where id=coalesce(p_target,v_actor.id) and room_code=v_code and (user_id is not null or is_companion);
     if not found then raise exception 'INVALID_TARGET'; end if;
     if v_target.death_failures>=3 then raise exception 'TARGET_DEAD'; end if;
   end if;
   if v_power.kind='heal' then
     v_amount:=v_amount+floor(random()*6)::int+1;
     update public.players set hp=least(max_hp,hp+v_amount),death_failures=0,death_successes=0 where id=v_target.id;
     v_log:=v_power.name||'：'||v_target.name||' 恢复 '||least(v_amount,v_target.max_hp-v_target.hp)||' HP';
   elsif v_power.kind='ward' then
     v_combat:=jsonb_set(v_combat,'{wards}',jsonb_set(coalesce(v_combat->'wards','{}'::jsonb),array[v_target.id::text],to_jsonb(greatest(v_amount,coalesce((v_combat->'wards'->>v_target.id::text)::int,0))),true));
     v_log:=v_power.name||'：'||v_target.name||' 下一次受攻击时 AC +'||v_amount;
   elsif v_power.kind='weaken' then
     v_idx:=public.campaign_enemy_index(v_combat->'enemies',p_target);
     v_foe:=v_combat->'enemies'->v_idx;
     v_combat:=jsonb_set(jsonb_set(v_combat,array['enemies',v_idx::text,'ac'],to_jsonb(greatest(8,(v_foe->>'ac')::int-v_amount))),array['enemies',v_idx::text,'attack_bonus'],to_jsonb(greatest(0,(v_foe->>'attack_bonus')::int-1)));
     v_log:=v_power.name||'：'||(v_foe->>'name')||' AC -'||v_amount||'、攻击 -1';
   elsif v_power.kind='damage' then
     v_idx:=public.campaign_enemy_index(v_combat->'enemies',p_target);
     v_foe:=v_combat->'enemies'->v_idx;
     v_stat:=case v_actor.class_name when '法师' then 3 when '牧师' then 4 when '游侠' then 4 when '吟游诗人' then 5 when '游荡者' then 1 when '圣武士' then 5 else 0 end;
     v_bonus:=floor(((v_actor.stats->>v_stat)::int-10)/2.0)::int+2+(v_actor.level-1)/4;
     v_roll:=floor(random()*20)::int+1;
     v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_foe->>'ac')::int) then 0 else v_amount+floor(random()*6)::int+1+case when v_roll=20 then v_amount else 0 end end;
     v_hp:=greatest(0,(v_foe->>'hp')::int-v_dmg);
     v_combat:=jsonb_set(v_combat,array['enemies',v_idx::text,'hp'],to_jsonb(v_hp));
     v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(public.campaign_enemy_hp(v_combat->'enemies')));
     v_log:=v_power.name||' → '||(v_foe->>'name')||' D20='||v_roll||'+'||v_bonus||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'，伤害 '||v_dmg;
   else raise exception 'UNKNOWN_EFFECT'; end if;

   if v_combat is not null and v_combat<>'null'::jsonb and (v_combat->>'hp')::int>0 then
     v_result:=public.campaign_finish_turn(v_code,v_combat,v_actor.id);
     v_state:=jsonb_set(v_state,'{combat}',v_result->'combat');
     v_log:=v_log||coalesce(v_result->>'log','');
   end if;
 end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 insert into public.messages(room_code,sender,body,kind) values(v_code,v_actor.name,v_log,'power');
 return public.party_snapshot(v_code);
end $$;
create or replace function public.party_area(p_code text,p_action text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
 v_code text:=upper(trim(coalesce(p_code,''))); v_uid uuid:=auth.uid(); v_actor public.players%rowtype;
 v_comp public.players%rowtype; v_target public.players%rowtype; v_state jsonb; v_combat jsonb;
 v_area public.uc_areas%rowtype; v_npc public.uc_npcs%rowtype; v_quest public.uc_quests%rowtype;
 v_item public.campaign_items%rowtype; v_battle public.uc_battles%rowtype;
 v_area_id text:=p_payload->>'area'; v_log text; v_record jsonb; v_stage jsonb; v_option jsonb;
 v_index integer; v_step integer; v_roll integer; v_bonus integer; v_dc integer; v_stat integer;
 v_hp integer; v_dmg integer; v_enemy jsonb; v_enemies jsonb; v_initiative jsonb; v_turn bigint;
 v_foe jsonb; v_result jsonb; v_outcome text; v_key text;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
 perform 1 from public.rooms where code=v_code for update;
 if not found then raise exception 'ROOM_NOT_FOUND'; end if;
 select * into v_actor from public.players where room_code=v_code and user_id=v_uid;
 if not found then raise exception 'NOT_MEMBER'; end if;
 select state into v_state from public.game_states where room_code=v_code for update;
 if not coalesce((v_state->>'started')::boolean,false) then raise exception 'NOT_STARTED'; end if;
 v_combat:=v_state->'combat';
 if p_action in ('companion_attack','companion_skill') then
   select * into v_comp from public.players where room_code=v_code and is_companion and id=coalesce((p_payload->>'companion')::bigint,0);
   if not found then raise exception 'NO_COMPANION'; end if;
   if v_combat is null or v_combat='null'::jsonb or coalesce((v_combat->>'hp')::int,0)<=0 then raise exception 'NO_COMBAT'; end if;
   if (v_combat->>'turn')::bigint<>v_comp.id then raise exception 'NOT_COMPANION_TURN'; end if;
   if v_comp.hp<=0 or v_comp.death_failures>=3 then raise exception 'DOWNED'; end if;
   v_index:=public.campaign_enemy_index(v_combat->'enemies',-coalesce((p_payload->>'enemy')::int,-1)-1);
   v_foe:=v_combat->'enemies'->v_index;
   v_roll:=floor(random()*20)::int+1;
   v_bonus:=4+(v_comp.level-1)/4+case when (v_combat->>'round')::int=1 then 2 else 0 end+case when p_action='companion_skill' then 1 else 0 end;
   if p_action='companion_skill' then
     if v_comp.ability_charges<1 then raise exception 'NO_ABILITY_CHARGES'; end if;
     update public.players set ability_charges=ability_charges-1 where id=v_comp.id;
   end if;
   v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_foe->>'ac')::int) then 0 else floor(random()*8)::int+1+v_bonus+case when p_action='companion_skill' then 8 else 3 end+case when v_roll=20 then floor(random()*8)::int+1 else 0 end end;
   v_hp:=greatest(0,(v_foe->>'hp')::int-v_dmg);
   v_combat:=jsonb_set(v_combat,array['enemies',v_index::text,'hp'],to_jsonb(v_hp));
   v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(public.campaign_enemy_hp(v_combat->'enemies')));
   v_log:=v_comp.name||case when p_action='companion_skill' then '使用主动能力「棱光箭」' else '射击' end||' → '||(v_foe->>'name')||' D20='||v_roll||'，伤害 '||v_dmg;
   v_result:=public.campaign_finish_turn(v_code,v_combat,v_comp.id);
   v_state:=jsonb_set(v_state,'{combat}',v_result->'combat');
   v_log:=v_log||coalesce(v_result->>'log','');
 elsif p_action='area_use' then
   select * into v_item from public.campaign_items where name=p_payload->>'item' and merchant='wonders' and slot='consumable';
   if not found or not (v_actor.inventory ? v_item.name) then raise exception 'ITEM_NOT_IN_BAG'; end if;
   if v_item.effect in ('heal','heal20') then
     select * into v_target from public.players where room_code=v_code and id=coalesce((p_payload->>'target')::bigint,v_actor.id) and (user_id is not null or is_companion);
     if not found or v_target.death_failures>=3 then raise exception 'INVALID_TARGET'; end if;
     update public.players set hp=least(max_hp,hp+case when v_item.effect='heal20' then 20 else 14 end),death_failures=0,death_successes=0 where id=v_target.id;
     v_log:=v_actor.name||'给'||v_target.name||'使用'||v_item.name||'，恢复生命。';
   elsif v_item.effect in ('ward','damage','damage20') then
     if v_combat is null or v_combat='null'::jsonb or (v_combat->>'hp')::int<=0 then raise exception 'NO_COMBAT'; end if;
     if (v_combat->>'turn')::bigint<>v_actor.id then raise exception 'NOT_YOUR_TURN'; end if;
     if v_actor.hp<=0 then raise exception 'DOWNED'; end if;
     if v_item.effect='ward' then
       select * into v_target from public.players where room_code=v_code and id=coalesce((p_payload->>'target')::bigint,v_actor.id) and (user_id is not null or is_companion);
       if not found then raise exception 'INVALID_TARGET'; end if;
       v_combat:=jsonb_set(v_combat,'{wards}',jsonb_set(coalesce(v_combat->'wards','{}'::jsonb),array[v_target.id::text],'4'::jsonb,true));
       v_log:=v_actor.name||'为'||v_target.name||'展开护盾卷轴，下一次受攻击 AC +4。';
     else
       v_index:=public.campaign_enemy_index(v_combat->'enemies',-coalesce((p_payload->>'enemy')::int,-1)-1);
       v_foe:=v_combat->'enemies'->v_index;
       v_roll:=floor(random()*20)::int+1; v_bonus:=floor(((v_actor.stats->>3)::int-10)/2.0)::int+2;
       v_dmg:=case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<(v_foe->>'ac')::int) then 0 else (case when v_item.effect='damage20' then 20 else 12 end)+floor(random()*7)::int+case when v_roll=20 then 8 else 0 end end;
       v_combat:=jsonb_set(v_combat,array['enemies',v_index::text,'hp'],to_jsonb(greatest(0,(v_foe->>'hp')::int-v_dmg)));
       v_combat:=jsonb_set(v_combat,'{hp}',to_jsonb(public.campaign_enemy_hp(v_combat->'enemies')));
       v_log:=v_actor.name||'使用'||v_item.name||' → '||(v_foe->>'name')||' D20='||v_roll||'，伤害 '||v_dmg;
     end if;
     v_result:=public.campaign_finish_turn(v_code,v_combat,v_actor.id);
     v_state:=jsonb_set(v_state,'{combat}',v_result->'combat');
     v_log:=v_log||coalesce(v_result->>'log','');
   else raise exception 'UNKNOWN_ITEM_EFFECT'; end if;
   update public.players set inventory=public.campaign_remove_one(inventory,v_item.name) where id=v_actor.id;
 else
   select * into v_area from public.uc_areas where id=v_area_id;
   if not found then raise exception 'UNKNOWN_AREA'; end if;
   if (v_state->>'chapter')::int<v_area.unlock_chapter then raise exception 'AREA_LOCKED'; end if;
   if v_combat is not null and v_combat<>'null'::jsonb and coalesce((v_combat->>'hp')::int,0)>0 then raise exception 'COMBAT_ACTIVE'; end if;
   if p_action='area_talk' then
     select * into v_npc from public.uc_npcs where id=p_payload->>'npc' and area=v_area.id;
     if not found then raise exception 'UNKNOWN_NPC'; end if;
     v_index:=coalesce((p_payload->>'topic')::int,-1);
     if v_index<0 or v_index>=jsonb_array_length(v_npc.topics) then raise exception 'INVALID_TOPIC'; end if;
     v_stage:=v_npc.topics->v_index;
     v_step:=coalesce((p_payload->>'choice')::int,-1);
     if v_step<0 or v_step>=jsonb_array_length(v_stage->'options') then raise exception 'INVALID_DIALOGUE_CHOICE'; end if;
     v_option:=v_stage->'options'->v_step;
     v_key:=v_npc.id||':'||v_index||':'||v_step;
     v_state:=jsonb_set(v_state,'{area_dialogue}',coalesce(v_state->'area_dialogue','[]'::jsonb)||jsonb_build_array(jsonb_build_object('npc',v_npc.id,'topic',v_index,'choice',v_step,'reply',v_option->>'reply','follow',v_option->>'follow')));
     v_state:=jsonb_set(v_state,'{area_attitudes}',jsonb_set(coalesce(v_state->'area_attitudes','{}'::jsonb),array[v_npc.id],to_jsonb(greatest(-5,least(5,coalesce((v_state->'area_attitudes'->>v_npc.id)::int,0)+coalesce((v_option->>'attitude')::int,0)))),true));
     if length(coalesce(v_option->>'flag',''))>0 and not coalesce(v_state->'flags','[]'::jsonb) ? (v_option->>'flag') then
       v_state:=jsonb_set(v_state,'{flags}',coalesce(v_state->'flags','[]'::jsonb)||to_jsonb(v_option->>'flag'));
     end if;
     v_log:=v_npc.name||'：「'||(v_stage->>'prompt')||'」 队伍：「'||(v_option->>'label')||'」 '||(v_option->>'reply')||' '||(v_option->>'follow');
   elsif p_action='area_inspect' then
     v_index:=coalesce((p_payload->>'place')::int,-1);
     if v_index<0 or v_index>=jsonb_array_length(v_area.places) then raise exception 'INVALID_PLACE'; end if;
     v_key:=v_area.id||':'||v_index;
     if coalesce(v_state->'area_inspected','[]'::jsonb) ? v_key then raise exception 'ALREADY_INSPECTED'; end if;
     v_roll:=floor(random()*20)::int+1;
     v_bonus:=floor(((v_actor.stats->>3)::int-10)/2.0)::int+case when v_actor.class_name in ('游荡者','法师') then 2 else 0 end;
     v_dc:=12+v_area.unlock_chapter/5;
     v_state:=jsonb_set(v_state,'{area_inspected}',coalesce(v_state->'area_inspected','[]'::jsonb)||to_jsonb(v_key));
     v_log:=(v_area.places->v_index->>0)||' · 调查 D20='||v_roll||'+'||v_bonus||' / DC '||v_dc||'：'||case when v_roll=20 or (v_roll<>1 and v_roll+v_bonus>=v_dc) then v_area.places->v_index->>1 else '现场有痕迹，但还不足以锁定来源；可以继续找 NPC 核对。' end;
     if v_roll=20 or (v_roll<>1 and v_roll+v_bonus>=v_dc) then
       v_state:=jsonb_set(v_state,'{clues}',coalesce(v_state->'clues','[]'::jsonb)||to_jsonb(v_area.places->v_index->>0));
     end if;
   elsif p_action in ('area_eat','area_drink') then
     if v_area.id<>'kegs' then raise exception 'TAVERN_ONLY'; end if;
     v_dc:=case when p_action='area_eat' then 6 else 4 end;
     update public.players set gold=gold-v_dc,hp=least(max_hp,hp+case when p_action='area_eat' then 10 else 5 end) where id=v_actor.id and gold>=v_dc and hp>0;
     if not found then raise exception 'NOT_ENOUGH_GOLD_OR_DOWNED'; end if;
     v_log:=v_actor.name||case when p_action='area_eat' then '吃了瑟拉的炖菜，支付 6 金币，恢复 10 HP。' else '喝了玛拉的热酒，支付 4 金币，恢复 5 HP。' end;
   elsif p_action='area_quest' then
     select * into v_quest from public.uc_quests where id=p_payload->>'quest';
     if not found then raise exception 'UNKNOWN_QUEST'; end if;
     v_record:=v_state->'side_quests'->v_quest.id;
     if v_record is null then
       if v_quest.area<>v_area.id then raise exception 'WRONG_AREA'; end if;
       v_record:=jsonb_build_object('status','进行中','step',0,'outcome',null);
       v_log:='接取支线：'||v_quest.name||'。'||v_quest.description;
     else
       if v_record->>'status'='已完成' then raise exception 'QUEST_COMPLETE'; end if;
       if v_record->>'status'='失败' then raise exception 'QUEST_FAILED'; end if;
       v_step:=(v_record->>'step')::int;
       v_stage:=v_quest.stages->v_step;
       if v_stage is null or v_stage->>'area'<>v_area.id then raise exception 'WRONG_AREA'; end if;
       if v_stage ? 'npc' and not exists(select 1 from jsonb_array_elements(coalesce(v_state->'area_dialogue','[]'::jsonb)) d where d->>'npc'=v_stage->>'npc') then raise exception 'TALK_TO_NPC_FIRST'; end if;
       if v_stage ? 'battle' then
         select * into v_battle from public.uc_battles where id=v_stage->>'battle';
         if v_battle.id is null then raise exception 'UNKNOWN_BATTLE'; end if;
         if not coalesce((v_record->>'battle_started')::boolean,false) then
           select jsonb_agg(jsonb_build_object('id',id,'roll',roll) order by roll desc,id),(array_agg(id order by roll desc,id))[1] into v_initiative,v_turn from (select id,floor(random()*20)::int+1 roll from public.players where room_code=v_code and (user_id is not null or is_companion) and hp>0 and death_failures<3) i;
           if v_turn is null then raise exception 'PARTY_DOWNED'; end if;
           v_enemies:='[]'::jsonb;
           for v_foe in select value from jsonb_array_elements(v_battle.foes) loop
             v_hp:=(v_foe->>1)::int+greatest(0,(select count(*) from public.players where room_code=v_code and user_id is not null)-2)*5;
             v_enemies:=v_enemies||jsonb_build_array(jsonb_build_object('name',v_foe->>0,'hp',v_hp,'max_hp',v_hp,'ac',(v_foe->>2)::int,'attack_bonus',(v_foe->>3)::int,'damage_min',(v_foe->>4)::int,'damage_die',(v_foe->>5)::int,'special',v_foe->>6));
           end loop;
           v_state:=jsonb_set(v_state,'{combat}',jsonb_build_object('name',v_battle.name,'side_quest',v_quest.id,'enemies',v_enemies,'hp',public.campaign_enemy_hp(v_enemies),'max_hp',public.campaign_enemy_hp(v_enemies),'turn',v_turn,'initiative',v_initiative,'round',1,'wards','{}'::jsonb));
           v_record:=jsonb_set(v_record,'{battle_started}','true'::jsonb);
           v_log:='支线战斗开始：'||v_battle.name||'。'||v_battle.intro;
         elsif v_combat is null or v_combat='null'::jsonb or v_combat->>'side_quest'<>v_quest.id or (v_combat->>'hp')::int>0 then raise exception 'BATTLE_NOT_WON';
         else v_record:=jsonb_set(jsonb_set(v_record,'{step}',to_jsonb(v_step+1)),'{status}',to_jsonb('可交付'::text)); v_log:='已完成战斗：'||v_battle.name||'。返回委托人交付证据。'; end if;
       elsif coalesce((v_stage->>'finish')::boolean,false) then
         if v_record->>'status'<>'可交付' then raise exception 'QUEST_NOT_READY'; end if;
         v_record:=jsonb_set(v_record,'{status}',to_jsonb('已完成'::text));
         update public.players set gold=gold+(v_quest.reward->>'gold')::int,experience=experience+(v_quest.reward->>'xp')::int,inventory=inventory||to_jsonb(v_quest.reward->>'item') where room_code=v_code and user_id is not null;
         v_log:='支线完成：'||v_quest.name||'。全队各获得 '||(v_quest.reward->>'gold')||' 金币、'||(v_quest.reward->>'xp')||' 经验及 '||(v_quest.reward->>'item')||'。';
         if v_quest.id='gate' and v_record->>'outcome'='protect' and not exists(select 1 from public.players where room_code=v_code and is_companion) then
           insert into public.players(room_code,name,class_name,is_companion,hp,max_hp,ac,stats,inventory,equipment,gold,level,ability_charges) values(v_code,'伊莉娅·棱光','游侠',true,28,28,15,'[12,17,14,13,15,12]'::jsonb,'[]'::jsonb,'["夜巡长弓"]'::jsonb,0,public.campaign_level((v_state->>'chapter')::int),2);
           v_log:=v_log||' 新伙伴已加入队伍：伊莉娅·棱光。';
         end if;
       else
         if v_stage ? 'options' then
           v_index:=coalesce((p_payload->>'option')::int,-1);
           if v_index<0 or v_index>=jsonb_array_length(v_stage->'options') then raise exception 'INVALID_QUEST_OPTION'; end if;
           v_option:=v_stage->'options'->v_index;
           v_outcome:=v_option->>2;
           v_log:=v_option->>1;
           if jsonb_array_length(v_option)>3 then v_stage:=jsonb_set(v_stage,'{skill}',to_jsonb(v_option->>3));v_stage:=jsonb_set(v_stage,'{dc}',v_option->4); end if;
         else v_log:=v_stage->>'text'; end if;
         if v_stage ? 'skill' then
           v_stat:=case v_stage->>'skill' when '运动' then 0 when '潜行' then 1 when '调查' then 3 when '奥秘' then 3 when '洞悉' then 4 when '求生' then 4 when '察觉' then 4 else 5 end;
           v_bonus:=floor(((v_actor.stats->>v_stat)::int-10)/2.0)::int+case when (v_actor.class_name='游荡者' and v_stage->>'skill' in ('调查','潜行','欺骗')) or (v_actor.class_name='法师' and v_stage->>'skill'='奥秘') or (v_actor.class_name='牧师' and v_stage->>'skill'='洞悉') or (v_actor.class_name='游侠' and v_stage->>'skill' in ('求生','察觉')) or (v_actor.class_name in ('圣武士','吟游诗人') and v_stage->>'skill'='说服') then 2 else 0 end;
           v_roll:=floor(random()*20)::int+1; v_dc:=(v_stage->>'dc')::int;
           v_log:=(v_stage->>'skill')||' D20='||v_roll||'+'||v_bonus||' / DC '||v_dc||case when v_roll=20 then ' 大成功' when v_roll=1 then ' 大失败' else '' end||'：'||case when v_roll=1 or (v_roll<>20 and v_roll+v_bonus<v_dc) then '暂未成功；可以再调查或由其他队员尝试。' else v_log end;
           if v_roll=1 or (v_roll<>20 and v_roll+v_bonus<v_dc) then
             update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
             insert into public.messages(room_code,sender,body,kind) values(v_code,v_actor.name,v_log,'area_quest');
             return public.party_snapshot(v_code);
           end if;
         end if;
         if v_outcome is not null then
           v_record:=jsonb_set(v_record,'{outcome}',to_jsonb(v_outcome));
           if v_outcome in ('bribe','sell') then
             update public.players set gold=gold+8 where id=v_actor.id;
             v_log:=v_log||' 私下收取 8 金币；委托人将记住这个决定。';
           elsif v_outcome in ('protect','guide','escort','patients','anonymous') then
             update public.players set experience=experience+8 where id=v_actor.id;
             v_log:=v_log||' 额外获得 8 经验。';
           end if;
           if v_outcome in ('threat','reveal','sell','bribe') then
             v_state:=jsonb_set(v_state,'{area_attitudes}',jsonb_set(coalesce(v_state->'area_attitudes','{}'::jsonb),array[v_quest.giver],to_jsonb(greatest(-5,coalesce((v_state->'area_attitudes'->>v_quest.giver)::int,0)-2)),true));
           end if;
           if v_quest.id='star' and v_outcome='bribe' then
             v_record:=jsonb_set(v_record,'{status}',to_jsonb('失败'::text));
             v_log:=v_log||' 星盘零件被转卖，委托失败。';
           end if;
         end if;
         if v_record->>'status'='失败' then
           v_state:=jsonb_set(v_state,'{side_quests}',jsonb_set(coalesce(v_state->'side_quests','{}'::jsonb),array[v_quest.id],v_record,true));
           update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
           insert into public.messages(room_code,sender,body,kind) values(v_code,v_actor.name,v_log,'area_quest');
           return public.party_snapshot(v_code);
         end if;
         v_step:=v_step+1;
         v_record:=jsonb_set(v_record,'{step}',to_jsonb(v_step));
         if coalesce((v_quest.stages->v_step->>'finish')::boolean,false) then v_record:=jsonb_set(v_record,'{status}',to_jsonb('可交付'::text)); end if;
       end if;
     end if;
     v_state:=jsonb_set(v_state,'{side_quests}',jsonb_set(coalesce(v_state->'side_quests','{}'::jsonb),array[v_quest.id],v_record,true));
   else raise exception 'UNKNOWN_AREA_ACTION'; end if;
 end if;
 update public.game_states set state=jsonb_set(v_state,'{version}',to_jsonb(coalesce((v_state->>'version')::int,0)+1)),updated_at=now() where room_code=v_code;
 insert into public.messages(room_code,sender,body,kind) values(v_code,v_actor.name,left(v_log,1000),p_action);
 return public.party_snapshot(v_code);
end $$;

revoke all on function public.party_area(text,text,jsonb) from public,anon,authenticated;
grant execute on function public.party_area(text,text,jsonb) to authenticated;
