import {areas,areaNpcs,areaQuests,areaBattles,wondersGoods} from './areas.js';
import {esc,button} from './views.js';
export function mapView(state,selected){
 const questStates=state.side_quests||{};
 return `<section class="card city-map"><div class="step-title"><h2>上城区 · 可探索区域</h2><small>酒馆与高堂常驻；大厅与城墙随主线解锁</small></div>${state.chapter===10?'<p class="good">新区域已解锁：至高大厅</p>':state.chapter===15?'<p class="good">新区域已解锁：上城区城墙</p>':''}<div class="area-grid">${areas.map(a=>{
  const open=state.chapter>=a.unlock;
  const relevant=areaQuests.filter(q=>q.area===a.id||q.stages[questStates[q.id]?.step]?.area===a.id);
  const marker=relevant.some(q=>questStates[q.id]?.status==='可交付'&&q.stages.at(-1).area===a.id)?'✓':relevant.some(q=>questStates[q.id]?.status==='进行中'&&q.stages[questStates[q.id].step]?.area===a.id)?'任务标记':relevant.some(q=>!questStates[q.id]&&q.area===a.id)?'!':'';
  return `<div class="area-tile ${selected===a.id?'active':''}"><img src="/images/area-${a.id}.webp" alt="${esc(a.name)}场景"><div><h3>${esc(a.name)} ${open?marker:'🔒'}</h3><p>${esc(a.description)}</p>${button(open?(selected===a.id?'正在探索':'进入'):'🔒 尚未解锁','enter_area',!open,`data-area="${a.id}"`)}</div></div>`;}).join('')}</div></section>`;
}
export function areaView(data,id){
 const a=areas.find(x=>x.id===id),s=data.state,mine=data.players.find(p=>p.id===data.me);
 if(!a||s.chapter<a.unlock)return '';
 const npc=areaNpcs.filter(n=>n.area===id),records=s.side_quests||{};
 return `<section class="card area-stage" id="region"><img class="area-banner" src="/images/area-${id}.webp" alt="${esc(a.name)}场景"><div class="area-caption"><p class="muted">UPPER CITY · ${esc(a.name)}</p><h2>${esc(a.name)}</h2><p>${esc(a.description)}</p>${button('← 返回上城区主界面','leave_area')}</div><h3>调查地点</h3><div class="explore-grid">${a.places.map(([title,desc],i)=>`<div class="encounter"><strong>${esc(title)}</strong><p>${esc(desc)}</p>${button((s.area_inspected||[]).includes(`${id}:${i}`)?'已调查':'调查 · D20','area_inspect',(s.area_inspected||[]).includes(`${id}:${i}`),`data-area="${id}" data-place="${i}"`)}</div>`).join('')}</div><h3>区域人物</h3><div class="area-npcs">${npc.map(n=>{
  const attitude=(s.area_attitudes||{})[n.id]||0;
  const history=(s.area_dialogue||[]).filter(h=>h.npc===n.id).slice(-3);
  const completed=areaQuests.filter(q=>q.giver===n.id&&records[q.id]?.status==='已完成');
  return `<details class="npc-card" data-detail="npc-${n.id}"><summary><strong>${esc(n.name)}</strong> · ${esc(n.role)} <small>态度 ${attitude>=2?'信任':attitude<=-2?'疏远':n.attitude}</small></summary><p>${esc(n.background)} · ${esc(n.personality)}</p><p class="npc-line">「${esc(completed.length?`上次${completed.map(q=>q.name).join('、')}的事多亏你们了。${n.intro}`:n.intro)}」</p>${n.topics.map((t,ti)=>`<details class="topic" data-detail="npc-${n.id}-topic-${ti}"><summary>${esc(t.prompt)}</summary>${t.options.map((o,oi)=>button(esc(o.label),'area_talk',false,`data-area="${id}" data-npc="${n.id}" data-topic="${ti}" data-choice="${oi}" class="choice"`)).join('')}</details>`).join('')}${history.length?`<h4>最近对话</h4>${history.map(h=>`<p class="dialogue-history">${esc(h.reply)} ${esc(h.follow)}</p>`).join('')}`:''}</details>`;}).join('')}</div>${id==='kegs'?`<section class="tavern-services"><h3>酒馆餐食</h3><p>炖菜恢复 10 HP · 热酒恢复 5 HP。由各玩家自己的金币支付。</p>${button('吃炖菜 · 6 金币','area_eat',mine.gold<6||mine.hp<=0,`data-area="${id}"`)} ${button('喝热酒 · 4 金币','area_drink',mine.gold<4||mine.hp<=0,`data-area="${id}"`)}</section>`:''}${id==='wonders'?`<section class="wonders-shop"><h3>高堂武器、装备与魔法商店</h3><p>金币 ${mine.gold} · 普通、精良、稀有和少量史诗装备随主线章节开放。</p>${wondersGoods.filter(g=>s.chapter>=g.unlock).map(g=>`<div class="shop-item"><div><strong>${esc(g.name)} <small>${esc(g.rarity)} · ${esc(g.slot)}</small></strong><p>${esc(g.description)}</p></div>${button(`${g.price} 金币 · 购买`,'buy',mine.gold<g.price||(g.slot!=='consumable'&&(mine.inventory.includes(g.name)||mine.equipment.includes(g.name))),`data-item="${esc(g.name)}"`)}</div>`).join('')}<h4>可使用的药水和卷轴</h4>${mine.inventory.filter(x=>wondersGoods.some(g=>g.name===x&&g.effect)).map(x=>`<div class="shop-item"><strong>${esc(x)}</strong>${button('使用','area_use',false,`data-item="${esc(x)}"`)}</div>`).join('')||'<p>背包里暂无高堂消耗品。</p>'}</section>`:''}<section class="side-missions"><h3>支线委托</h3>${areaQuests.filter(q=>q.area===id||q.stages[records[q.id]?.step]?.area===id).map(q=>{
 const r=records[q.id],stage=r&&q.stages[r.step];
 if(!r)return `<div class="mission"><h4>! ${esc(q.name)}</h4><p>${esc(q.description)}</p><p>委托人：${esc(areaNpcs.find(n=>n.id===q.giver)?.name)}</p>${button('接取支线','area_quest',false,`data-area="${id}" data-quest="${q.id}"`)}</div>`;
 if(r.status==='失败')return `<div class="mission"><h4>✕ ${esc(q.name)}</h4><p>任务失败 · 决定已经记录，其他支线和主线仍可继续。</p></div>`;
 if(r.status==='已完成')return `<div class="mission"><h4>✓ ${esc(q.name)}</h4><p>已完成 · 获得 ${q.reward.gold} 金币、${q.reward.xp} 经验和 ${esc(q.reward.item)}。</p></div>`;
 return `<div class="mission"><h4>${r.status==='可交付'?'✓':'任务标记'} ${esc(q.name)} · ${esc(r.status)}</h4><p>${esc(stage?.text)}</p><p>当前目标：${esc(stage?.label)} ${stage?.skill?`· ${esc(stage.skill)} DC ${stage.dc}`:''}</p>${stage?.npc&&!((s.area_dialogue||[]).some(h=>h.npc===stage.npc))?`<p class="muted">先与 ${esc(areaNpcs.find(n=>n.id===stage.npc)?.name)} 交谈。</p>`:''}${stage?.area===id?(stage.options?stage.options.map((o,i)=>button(esc(o[0]),'area_quest',false,`data-area="${id}" data-quest="${q.id}" data-option="${i}" class="choice"`)).join(''):button(stage.battle?(r.battle_started?'战斗胜利后继续':'⚔️ 进入支线战斗'):stage.finish?'交付任务并领取奖励':'继续调查','area_quest',(stage.battle&&r.battle_started&&s.combat?.hp>0)||(stage.npc&&!((s.area_dialogue||[]).some(h=>h.npc===stage.npc))),`data-area="${id}" data-quest="${q.id}"`)):`<p class="muted">下一站：${esc(areas.find(a=>a.id===stage?.area)?.name||'未知')}</p>`}</div>`;
 }).join('')||'<p>此处暂无可接委托，调查 NPC 或推进已有任务。</p>'}</section></section>`;
}
export function questJournal(s){return `<h3>区域支线任务日志</h3>${areaQuests.map(q=>{const r=s.side_quests?.[q.id],stage=r&&q.stages[r.step],status=r?.status||'未接取';return `<details class="mission"><summary>${esc(q.name)} · 支线 · ${esc(status)}</summary><p>${esc(q.description)}</p><p>阶段：${r?`${Math.min(r.step+1,q.stages.length)}/${q.stages.length}`:'尚未开始'} · 当前目标：${esc(stage?.label|| (status==='已完成'?'已结算':'与委托人交谈'))}</p><p>地点：${esc(areas.find(a=>a.id===(stage?.area||q.area))?.name)}</p><p>奖励：${q.reward.gold} 金币、${q.reward.xp} 经验、${esc(q.reward.item)}</p></details>`}).join('')}`;}
export function sideBattleArt(s){return s.combat?.side_quest?areaBattles.find(b=>b.id===areaQuests.find(q=>q.id===s.combat.side_quest)?.stages.find(x=>x.battle)?.battle):null;}
