// Public descriptions only. Availability, prices and bonuses are enforced by SQL.
export const merchants = [
  {
    id: "gate",
    name: "城门补给商艾米",
    chapter: 0,
    description: "为初入城的冒险者准备基础武器和药剂。",
  },
  {
    id: "market",
    name: "灰市铁匠穆雷",
    chapter: 5,
    description: "调查灰市后开放改良武器与轻甲。",
  },
  {
    id: "clock",
    name: "钟楼工坊格雷",
    chapter: 10,
    description: "以钟楼零件打造精密装备。",
  },
  {
    id: "salt",
    name: "盐井锻造师乌伦",
    chapter: 15,
    description: "地下矿石能锻成更沉重的武器。",
  },
  {
    id: "mirror",
    name: "镜厅藏品商菲娅",
    chapter: 20,
    description: "听证会前出售稀有防具。",
  },
  {
    id: "dawn",
    name: "黎明铸匠凯尔",
    chapter: 25,
    description: "决战前为队伍准备最后一批装备。",
  },
];
export const items = [
  {
    name: "治疗药水",
    merchant: "gate",
    chapter: 0,
    slot: "consumable",
    price: 10,
    attack: 0,
    damage: 0,
    ac: 0,
    description: "恢复 8 HP。",
  },
  {
    name: "盾牌",
    merchant: "gate",
    chapter: 0,
    slot: "offhand",
    price: 30,
    attack: 0,
    damage: 0,
    ac: 1,
    description: "装备后 AC +1。",
  },
  {
    name: "城门长剑",
    merchant: "gate",
    chapter: 0,
    slot: "weapon",
    price: 18,
    attack: 1,
    damage: 2,
    ac: 0,
    description: "攻击检定 +1，伤害 +2。",
  },
  {
    name: "灰市长枪",
    merchant: "market",
    chapter: 5,
    slot: "weapon",
    price: 32,
    attack: 2,
    damage: 3,
    ac: 0,
    description: "攻击检定 +2，伤害 +3。",
  },
  {
    name: "工人护肩",
    merchant: "market",
    chapter: 5,
    slot: "armor",
    price: 25,
    attack: 0,
    damage: 0,
    ac: 1,
    description: "装备后 AC +1。",
  },
  {
    name: "钟芯刺剑",
    merchant: "clock",
    chapter: 10,
    slot: "weapon",
    price: 46,
    attack: 3,
    damage: 4,
    ac: 0,
    description: "攻击检定 +3，伤害 +4。",
  },
  {
    name: "齿轮胸甲",
    merchant: "clock",
    chapter: 10,
    slot: "armor",
    price: 40,
    attack: 0,
    damage: 0,
    ac: 2,
    description: "装备后 AC +2。",
  },
  {
    name: "盐井战斧",
    merchant: "salt",
    chapter: 15,
    slot: "weapon",
    price: 60,
    attack: 4,
    damage: 5,
    ac: 0,
    description: "攻击检定 +4，伤害 +5。",
  },
  {
    name: "深井护符",
    merchant: "salt",
    chapter: 15,
    slot: "charm",
    price: 50,
    attack: 0,
    damage: 0,
    ac: 2,
    description: "装备后 AC +2。",
  },
  {
    name: "镜刃",
    merchant: "mirror",
    chapter: 20,
    slot: "weapon",
    price: 75,
    attack: 5,
    damage: 6,
    ac: 0,
    description: "攻击检定 +5，伤害 +6。",
  },
  {
    name: "议会卫甲",
    merchant: "mirror",
    chapter: 20,
    slot: "armor",
    price: 70,
    attack: 0,
    damage: 0,
    ac: 3,
    description: "装备后 AC +3。",
  },
  {
    name: "黎明钢剑",
    merchant: "dawn",
    chapter: 25,
    slot: "weapon",
    price: 90,
    attack: 6,
    damage: 7,
    ac: 0,
    description: "攻击检定 +6，伤害 +7。",
  },
  {
    name: "誓约披风",
    merchant: "dawn",
    chapter: 25,
    slot: "charm",
    price: 85,
    attack: 0,
    damage: 0,
    ac: 3,
    description: "装备后 AC +3。",
  },
];
